In [93]:
import pandas as pd

In [94]:
fleni100_match = pd.read_csv("~/Downloads/Fleni/fleni100/match.csv")
fleni100_match

     Unnamed: 0  Unnamed: 0.1                                       anon_id  \
0             0             0  601894e9-7192ca44-617903f9-b7775028-b7db3c01
1             1             1                                           NaN
2             2             2  26f052fa-48d0929f-43515de0-ab857928-4ee712ec
3             3             3  9c673f58-f5bfbaf0-ff226082-410ef24e-e7d8ff4a
4             4             4  0f5ab5b2-c7051e97-42563753-f7f14410-29b463dd
..          ...           ...                                           ...
234         234           255  50b4f5c1-43cbe80d-0d499cc4-525a4752-cb02a377
235         235           256  f301e2e5-ef504c7a-adfe1c95-ef3b1c97-75b21599
236         236           257  c0ed3dcd-9c7e8e50-067ce990-f4417a65-4c5b379f
237         237           258  179ffba1-0dbc255c-ec399ad4-962ed53a-a19a0bff
238         238           259  f1b927dc-db9ba0ef-0e204f32-8ebbc85f-be0fe49a

                            Unnamed: 1  Participant ID                Name  \
0                                  NaN          3370.0             NICOLAS
1    no hay PET. Las RM son desde 2020          8964.0        MARIA TERESA
2                                  NaN         13512.0        MARTA SUSANA
3                                  NaN         13778.0    LIDIA AIDA NOEMI
4                                  NaN         15076.0  ALEJANDRA PATRICIA
..                                 ...             ...                 ...
234                                NaN        703380.0           FERNANDO
235                                NaN        712848.0       LIVIA LUCIANA
236                                NaN        715946.0         PEDRO MARIA
237                                NaN        717824.0            PATRICIO
238                                NaN        718566.0   GUILLERMO AUGUSTO

             Surname                 Nombre T1        AN_MRI    Date_MRI  ...  \
0               RIGA           3D fSPGR-IRprep  9.275000e+12  2013-07-04  ...
1    BILBAO LA VIEJA                       NaN  9.275001e+12         NaN  ...
2           EVRANIAN                  FSPGR 3D  9.275000e+12  2015-06-29  ...
3           WILENSKY   Accelerated Ax IR-FSPGR  9.275001e+12  2019-06-19  ...
4            FONTANA  Accelerated SAG IR-FSPGR  9.275001e+12  2017-08-04  ...
..               ...                       ...           ...         ...  ...
234          BARROS                Ax FSPGR 3D  9.275001e+12  2020-09-11  ...
235             DEON   Accelerated Ax IR-FSPGR  9.275001e+12  2021-01-08  ...
236           PAILHE   Accelerated Ax IR-FSPGR  9.275001e+12  2021-02-11  ...
237           MURPHY               Ax FSPGR 3D  9.275001e+12  2021-05-16  ...
238          BASILIO   Accelerated Ax IR-FSPGR  9.275001e+12  2021-04-03  ...

     gctx-bilat-occipital_rel gctx-bilat-occipital_per  \
0                    0.027904                     11.9
1                         NaN                      NaN
2                    0.036981                     93.7
3                    0.027322                      8.9
4                    0.036672                     83.6
..                        ...                      ...
234                  0.018745                      1.0
235                  0.030842                     44.2
236                  0.031266                     34.0
237                  0.023596                      1.0
238                  0.029793                     24.0

    gctx-bilat-parietal_abs gctx-bilat-parietal_rel gctx-bilat-parietal_per  \
0              1.334525e+16                0.086964                    54.5
1                       NaN                     NaN                     NaN
2              1.157804e+16                0.082528                    35.8
3              9.642489e+15                0.070050                     1.9
4              1.333215e+16                0.088888                    46.6
..                      ...                     ...                     ...
234            1.133951e+14                0.074534                     3.3
235            1.064728e+16                0.076410                    14.9
236            1.367143e+15                0.085687                    36.6
237            1.158759e+16                0.065948                     1.0
238            1.156662e+16                0.074629                     4.5

    gctx-bilat-temporal_abs gctx-bilat-temporal_rel gctx-bilat-temporal_per  \
0              1.035334e+16                0.067468                    36.4
1                       NaN                     NaN                     NaN
2              9.217053e+15                0.065699                    29.7
3              7.203079e+15                0.052328                     1.0
4              9.954130e+15                0.066366                    16.3
..                      ...                     ...                     ...
234            9.487423e+15                0.062360                     5.5
235            8.270453e+15                0.059353                     5.2
236            1.054083e+16                0.066066                    19.6
237            1.034558e+16                0.058879                     1.0
238            1.045008e+16                0.067425                    34.1

    ,anon_id,Unnamed: 1,Participant ID,Name,Surname,Nombre T1,AN_MRI,Date_MRI,Age at diagnostic visit (in years),Diagnostico Presuntivo,Age at death,Age at symptom onset,Sex,Education,APOE4 status,CSF amyloid positivity (yes/no),PET PiB amyloid positivity (yes/no),PET tau positivity (yes/no),FDG PET (hypometabolism profile),diag,unknown_abs,unknown_rel,unknown_per,left-cerebral-white-matter_abs,left-cerebral-white-matter_rel,left-cerebral-white-matter_per,left-cerebral-cortex_abs,left-cerebral-cortex_rel,left-cerebral-cortex_per,supratentorial_ventricles_abs,supratentorial_ventricles_rel,supratentorial_ventricles_per,left-cerebellum-white-matter_abs,left-cerebellum-white-matter_rel,left-cerebellum-white-matter_per,left-cerebellum-cortex_abs,left-cerebellum-cortex_rel,left-cerebellum-cortex_per,left-thalamus-proper*_abs,left-thalamus-proper*_rel,left-thalamus-proper*_per,left-caudate_abs,left-caudate_rel,left-caudate_per,left-putamen_abs,left-putamen_rel,left-putamen_per,left-pallidum_abs,left-pallidum_rel,left-pallidum_per,4th-ventricle_abs,4th-ventricle_rel,4th-ventricle_per,brain-stem_abs,brain-stem_rel,brain-stem_per,left-hippocampus_abs,left-hippocampus_rel,left-hippocampus_per,left-amygdala_abs,left-amygdala_rel,left-amygdala_per,csf-freesurfer_abs,csf-freesurfer_rel,csf-freesurfer_per,left-accumbens-area_abs,left-accumbens-area_rel,left-accumbens-area_per,left-ventraldc_abs,left-ventraldc_rel,left-ventraldc_per,right-cerebral-white-matter_abs,right-cerebral-white-matter_rel,right-cerebral-white-matter_per,right-cerebral-cortex_abs,right-cerebral-cortex_rel,right-cerebral-cortex_per,right-cerebellum-white-matter_abs,right-cerebellum-white-matter_rel,right-cerebellum-white-matter_per,right-cerebellum-cortex_abs,right-cerebellum-cortex_rel,right-cerebellum-cortex_per,right-thalamus-proper*_abs,right-thalamus-proper*_rel,right-thalamus-proper*_per,right-caudate_abs,right-caudate_rel,right-caudate_per,right-putamen_abs,right-putamen_rel,right-putamen_per,right-pallidum_abs,right-pallidum_rel,right-pallidum_per,right-hippocampus_abs,right-hippocampus_rel,right-hippocampus_per,right-amygdala_abs,right-amygdala_rel,right-amygdala_per,right-accumbens-area_abs,right-accumbens-area_rel,right-accumbens-area_per,right-ventraldc_abs,right-ventraldc_rel,right-ventraldc_per,corpus_callosum_abs,corpus_callosum_rel,corpus_callosum_per,ctx-lh-superior+transversetemporal_abs,ctx-lh-superior+transversetemporal_rel,ctx-lh-superior+transversetemporal_per,ctx-lh-cingulo_abs,ctx-lh-cingulo_rel,ctx-lh-cingulo_per,ctx-lh-frontalsuperiorandmiddle_abs,ctx-lh-frontalsuperiorandmiddle_rel,ctx-lh-frontalsuperiorandmiddle_per,ctx-lh-superiorparietal+postcentral_abs,ctx-lh-superiorparietal+postcentral_rel,ctx-lh-superiorparietal+postcentral_per,ctx-lh-inferiorparietal_abs,ctx-lh-inferiorparietal_rel,ctx-lh-inferiorparietal_per,ctx-lh-medialoccipital_abs,ctx-lh-medialoccipital_rel,ctx-lh-medialoccipital_per,ctx-lh-parahippocampal+fusiform+entorhinal_abs,ctx-lh-parahippocampal+fusiform+entorhinal_rel,ctx-lh-parahippocampal+fusiform+entorhinal_per,ctx-lh-middle+inferiortemporal+pole_abs,ctx-lh-middle+inferiortemporal+pole_rel,ctx-lh-middle+inferiortemporal+pole_per,ctx-lh-lateraloccipital_abs,ctx-lh-lateraloccipital_rel,ctx-lh-lateraloccipital_per,ctx-lh-orbitofrontal_abs,ctx-lh-orbitofrontal_rel,ctx-lh-orbitofrontal_per,ctx-lh-precentral+paracentral_abs,ctx-lh-precentral+paracentral_rel,ctx-lh-precentral+paracentral_per,ctx-lh-frontalinferior_abs,ctx-lh-frontalinferior_rel,ctx-lh-frontalinferior_per,ctx-lh-precuneus_abs,ctx-lh-precuneus_rel,ctx-lh-precuneus_per,ctx-lh-insula_abs,ctx-lh-insula_rel,ctx-lh-insula_per,ctx-rh-superior+transversetemporal_abs,ctx-rh-superior+transversetemporal_rel,ctx-rh-superior+transversetemporal_per,ctx-rh-cingulo_abs,ctx-rh-cingulo_rel,ctx-rh-cingulo_per,ctx-rh-frontalsuperiorandmiddle_abs,ctx-rh-frontalsuperiorandmiddle_rel,ctx-rh-frontalsuperiorandmiddle_per,ctx-rh-superiorparietal+postcentral_abs,ctx-rh-superiorparietal+postcentral_rel,ctx-rh-superiorparietal+postcentral_per,ctx-rh-inferiorparietal_abs,ctx-rh-inferiorparietal_rel,ctx-rh-inferiorparietal_per,ctx-rh-medialoccipital_abs,ctx-rh-medialoccipital_rel,ctx-rh-medialoccipital_per,ctx-rh-parahippocampal+fusiform+entorhinal_abs,ctx-rh-parahippocampal+fusiform+entorhinal_rel,ctx-rh-parahippocampal+fusiform+entorhinal_per,ctx-rh-middle+inferiortemporal+pole_abs,ctx-rh-middle+inferiortemporal+pole_rel,ctx-rh-middle+inferiortemporal+pole_per,ctx-rh-lateraloccipital_abs,ctx-rh-lateraloccipital_rel,ctx-rh-lateraloccipital_per,ctx-rh-orbitofrontal_abs,ctx-rh-orbitofrontal_rel,ctx-rh-orbitofrontal_per,ctx-rh-precentral+paracentral_abs,ctx-rh-precentral+paracentral_rel,ctx-rh-precentral+paracentral_per,ctx-rh-frontalinferior_abs,ctx-rh-frontalinferior_rel,ctx-rh-frontalinferior_per,ctx-rh-precuneus_abs,ctx-rh-precuneus_rel,ctx-rh-precuneus_per,ctx-rh-insula_abs,ctx-rh-insula_rel,ctx-rh-insula_per,brain_abs,brain_rel,brain_per,wm_abs,wm_rel,wm_per,gm_abs,gm_rel,gm_per,csf_abs,csf_rel,csf_per,cerebellum_abs,cerebellum_rel,cerebellum_per,bpf_abs,bpf_rel,bpf_per,evans_abs,evans_rel,evans_per,gctx-lh-frontal_abs,gctx-lh-frontal_rel,gctx-lh-frontal_per,gctx-lh-insula_abs,gctx-lh-insula_rel,gctx-lh-insula_per,gctx-lh-occipital_abs,gctx-lh-occipital_rel,gctx-lh-occipital_per,gctx-lh-parietal_abs,gctx-lh-parietal_rel,gctx-lh-parietal_per,gctx-lh-temporal_abs,gctx-lh-temporal_rel,gctx-lh-temporal_per,gctx-rh-frontal_abs,gctx-rh-frontal_rel,gctx-rh-frontal_per,gctx-rh-insula_abs,gctx-rh-insula_rel,gctx-rh-insula_per,gctx-rh-occipital_abs,gctx-rh-occipital_rel,gctx-rh-occipital_per,gctx-rh-parietal_abs,gctx-rh-parietal_rel,gctx-rh-parietal_per,gctx-rh-temporal_abs,gctx-rh-temporal_rel,gctx-rh-temporal_per,gctx-bilat-frontal_abs,gctx-bilat-frontal_rel,gctx-bilat-frontal_per,gctx-bilat-insula_abs,gctx-bilat-insula_rel,gctx-bilat-insula_per,gctx-bilat-occipital_abs,gctx-bilat-occipital_rel,gctx-bilat-occipital_per,gctx-bilat-parietal_abs,gctx-bilat-parietal_rel,gctx-bilat-parietal_per,gctx-bilat-temporal_abs,gctx-bilat-temporal_rel,gctx-bilat-temporal_per  \
0    0,601894e9-7192ca44-617903f9-b7775028-b7db3c01...
1    1,,no hay PET. Las RM son desde 2020,8964.0,MA...
2    2,26f052fa-48d0929f-43515de0-ab857928-4ee712ec...
3    3,9c673f58-f5bfbaf0-ff226082-410ef24e-e7d8ff4a...
4    4,0f5ab5b2-c7051e97-42563753-f7f14410-29b463dd...
..                                                 ...
234  255,50b4f5c1-43cbe80d-0d499cc4-525a4752-cb02a3...
235  256,f301e2e5-ef504c7a-adfe1c95-ef3b1c97-75b215...
236  257,c0ed3dcd-9c7e8e50-067ce990-f4417a65-4c5b37...
237  258,179ffba1-0dbc255c-ec399ad4-962ed53a-a19a0b...
238  259,f1b927dc-db9ba0ef-0e204f32-8ebbc85f-be0fe4...

                                           pet_id
0    b87479c8-641ec909-8b8effc1-9b58a18a-573f8414
1                                               -
2    e5a4f8b8-f6ad7d45-52b4b6e8-f3ebf6cd-c8e8f25b
3    c96cbd4d-f9cfda98-8bd71bc1-e26e87e3-e25c6d50
4    b172e084-61708876-5cb503da-b65f4f85-e1c4e110
..                                            ...
234                                             -
235                                             -
236                                             -
237                                             -
238                                             -

[239 rows x 264 columns]

In [95]:
list(fleni100_match.columns)

['Unnamed: 0',
 'Unnamed: 0.1',
 'anon_id',
 'Unnamed: 1',
 'Participant ID',
 'Name',
 'Surname',
 'Nombre T1',
 'AN_MRI',
 'Date_MRI',
 'Age at diagnostic visit (in years)',
 'Diagnostico Presuntivo',
 'Age at death',
 'Age at symptom onset',
 'Sex',
 'Education',
 'APOE4 status',
 'CSF amyloid positivity (yes/no)',
 'PET PiB amyloid positivity (yes/no)',
 'PET tau positivity (yes/no)',
 'FDG PET (hypometabolism profile)',
 'diag',
 'unknown_abs',
 'unknown_rel',
 'unknown_per',
 'left-cerebral-white-matter_abs',
 'left-cerebral-white-matter_rel',
 'left-cerebral-white-matter_per',
 'left-cerebral-cortex_abs',
 'left-cerebral-cortex_rel',
 'left-cerebral-cortex_per',
 'supratentorial_ventricles_abs',
 'supratentorial_ventricles_rel',
 'supratentorial_ventricles_per',
 'left-cerebellum-white-matter_abs',
 'left-cerebellum-white-matter_rel',
 'left-cerebellum-white-matter_per',
 'left-cerebellum-cortex_abs',
 'left-cerebellum-cortex_rel',
 'left-cerebellum-cortex_per',
 'left-thalamus-proper*_abs',
 'left-thalamus-proper*_rel',
 'left-thalamus-proper*_per',
 'left-caudate_abs',
 'left-caudate_rel',
 'left-caudate_per',
 'left-putamen_abs',
 'left-putamen_rel',
 'left-putamen_per',
 'left-pallidum_abs',
 'left-pallidum_rel',
 'left-pallidum_per',
 '4th-ventricle_abs',
 '4th-ventricle_rel',
 '4th-ventricle_per',
 'brain-stem_abs',
 'brain-stem_rel',
 'brain-stem_per',
 'left-hippocampus_abs',
 'left-hippocampus_rel',
 'left-hippocampus_per',
 'left-amygdala_abs',
 'left-amygdala_rel',
 'left-amygdala_per',
 'csf-freesurfer_abs',
 'csf-freesurfer_rel',
 'csf-freesurfer_per',
 'left-accumbens-area_abs',
 'left-accumbens-area_rel',
 'left-accumbens-area_per',
 'left-ventraldc_abs',
 'left-ventraldc_rel',
 'left-ventraldc_per',
 'right-cerebral-white-matter_abs',
 'right-cerebral-white-matter_rel',
 'right-cerebral-white-matter_per',
 'right-cerebral-cortex_abs',
 'right-cerebral-cortex_rel',
 'right-cerebral-cortex_per',
 'right-cerebellum-white-matter_abs',
 'right-cerebellum-white-matter_rel',
 'right-cerebellum-white-matter_per',
 'right-cerebellum-cortex_abs',
 'right-cerebellum-cortex_rel',
 'right-cerebellum-cortex_per',
 'right-thalamus-proper*_abs',
 'right-thalamus-proper*_rel',
 'right-thalamus-proper*_per',
 'right-caudate_abs',
 'right-caudate_rel',
 'right-caudate_per',
 'right-putamen_abs',
 'right-putamen_rel',
 'right-putamen_per',
 'right-pallidum_abs',
 'right-pallidum_rel',
 'right-pallidum_per',
 'right-hippocampus_abs',
 'right-hippocampus_rel',
 'right-hippocampus_per',
 'right-amygdala_abs',
 'right-amygdala_rel',
 'right-amygdala_per',
 'right-accumbens-area_abs',
 'right-accumbens-area_rel',
 'right-accumbens-area_per',
 'right-ventraldc_abs',
 'right-ventraldc_rel',
 'right-ventraldc_per',
 'corpus_callosum_abs',
 'corpus_callosum_rel',
 'corpus_callosum_per',
 'ctx-lh-superior+transversetemporal_abs',
 'ctx-lh-superior+transversetemporal_rel',
 'ctx-lh-superior+transversetemporal_per',
 'ctx-lh-cingulo_abs',
 'ctx-lh-cingulo_rel',
 'ctx-lh-cingulo_per',
 'ctx-lh-frontalsuperiorandmiddle_abs',
 'ctx-lh-frontalsuperiorandmiddle_rel',
 'ctx-lh-frontalsuperiorandmiddle_per',
 'ctx-lh-superiorparietal+postcentral_abs',
 'ctx-lh-superiorparietal+postcentral_rel',
 'ctx-lh-superiorparietal+postcentral_per',
 'ctx-lh-inferiorparietal_abs',
 'ctx-lh-inferiorparietal_rel',
 'ctx-lh-inferiorparietal_per',
 'ctx-lh-medialoccipital_abs',
 'ctx-lh-medialoccipital_rel',
 'ctx-lh-medialoccipital_per',
 'ctx-lh-parahippocampal+fusiform+entorhinal_abs',
 'ctx-lh-parahippocampal+fusiform+entorhinal_rel',
 'ctx-lh-parahippocampal+fusiform+entorhinal_per',
 'ctx-lh-middle+inferiortemporal+pole_abs',
 'ctx-lh-middle+inferiortemporal+pole_rel',
 'ctx-lh-middle+inferiortemporal+pole_per',
 'ctx-lh-lateraloccipital_abs',
 'ctx-lh-lateraloccipital_rel',
 'ctx-lh-lateraloccipital_per',
 'ctx-lh-orbitofrontal_abs',
 'ctx-lh-orbitofrontal_rel',
 'ctx-lh-orbitofrontal_per',
 'ctx-lh-precentral+paracentral_abs',
 'ctx-lh-precentral+paracentral_rel',
 'ctx-lh-precentral+paracentral_per',
 'ctx-lh-frontalinferior_abs',
 'ctx-lh-frontalinferior_rel',
 'ctx-lh-frontalinferior_per',
 'ctx-lh-precuneus_abs',
 'ctx-lh-precuneus_rel',
 'ctx-lh-precuneus_per',
 'ctx-lh-insula_abs',
 'ctx-lh-insula_rel',
 'ctx-lh-insula_per',
 'ctx-rh-superior+transversetemporal_abs',
 'ctx-rh-superior+transversetemporal_rel',
 'ctx-rh-superior+transversetemporal_per',
 'ctx-rh-cingulo_abs',
 'ctx-rh-cingulo_rel',
 'ctx-rh-cingulo_per',
 'ctx-rh-frontalsuperiorandmiddle_abs',
 'ctx-rh-frontalsuperiorandmiddle_rel',
 'ctx-rh-frontalsuperiorandmiddle_per',
 'ctx-rh-superiorparietal+postcentral_abs',
 'ctx-rh-superiorparietal+postcentral_rel',
 'ctx-rh-superiorparietal+postcentral_per',
 'ctx-rh-inferiorparietal_abs',
 'ctx-rh-inferiorparietal_rel',
 'ctx-rh-inferiorparietal_per',
 'ctx-rh-medialoccipital_abs',
 'ctx-rh-medialoccipital_rel',
 'ctx-rh-medialoccipital_per',
 'ctx-rh-parahippocampal+fusiform+entorhinal_abs',
 'ctx-rh-parahippocampal+fusiform+entorhinal_rel',
 'ctx-rh-parahippocampal+fusiform+entorhinal_per',
 'ctx-rh-middle+inferiortemporal+pole_abs',
 'ctx-rh-middle+inferiortemporal+pole_rel',
 'ctx-rh-middle+inferiortemporal+pole_per',
 'ctx-rh-lateraloccipital_abs',
 'ctx-rh-lateraloccipital_rel',
 'ctx-rh-lateraloccipital_per',
 'ctx-rh-orbitofrontal_abs',
 'ctx-rh-orbitofrontal_rel',
 'ctx-rh-orbitofrontal_per',
 'ctx-rh-precentral+paracentral_abs',
 'ctx-rh-precentral+paracentral_rel',
 'ctx-rh-precentral+paracentral_per',
 'ctx-rh-frontalinferior_abs',
 'ctx-rh-frontalinferior_rel',
 'ctx-rh-frontalinferior_per',
 'ctx-rh-precuneus_abs',
 'ctx-rh-precuneus_rel',
 'ctx-rh-precuneus_per',
 'ctx-rh-insula_abs',
 'ctx-rh-insula_rel',
 'ctx-rh-insula_per',
 'brain_abs',
 'brain_rel',
 'brain_per',
 'wm_abs',
 'wm_rel',
 'wm_per',
 'gm_abs',
 'gm_rel',
 'gm_per',
 'csf_abs',
 'csf_rel',
 'csf_per',
 'cerebellum_abs',
 'cerebellum_rel',
 'cerebellum_per',
 'bpf_abs',
 'bpf_rel',
 'bpf_per',
 'evans_abs',
 'evans_rel',
 'evans_per',
 'gctx-lh-frontal_abs',
 'gctx-lh-frontal_rel',
 'gctx-lh-frontal_per',
 'gctx-lh-insula_abs',
 'gctx-lh-insula_rel',
 'gctx-lh-insula_per',
 'gctx-lh-occipital_abs',
 'gctx-lh-occipital_rel',
 'gctx-lh-occipital_per',
 'gctx-lh-parietal_abs',
 'gctx-lh-parietal_rel',
 'gctx-lh-parietal_per',
 'gctx-lh-temporal_abs',
 'gctx-lh-temporal_rel',
 'gctx-lh-temporal_per',
 'gctx-rh-frontal_abs',
 'gctx-rh-frontal_rel',
 'gctx-rh-frontal_per',
 'gctx-rh-insula_abs',
 'gctx-rh-insula_rel',
 'gctx-rh-insula_per',
 'gctx-rh-occipital_abs',
 'gctx-rh-occipital_rel',
 'gctx-rh-occipital_per',
 'gctx-rh-parietal_abs',
 'gctx-rh-parietal_rel',
 'gctx-rh-parietal_per',
 'gctx-rh-temporal_abs',
 'gctx-rh-temporal_rel',
 'gctx-rh-temporal_per',
 'gctx-bilat-frontal_abs',
 'gctx-bilat-frontal_rel',
 'gctx-bilat-frontal_per',
 'gctx-bilat-insula_abs',
 'gctx-bilat-insula_rel',
 'gctx-bilat-insula_per',
 'gctx-bilat-occipital_abs',
 'gctx-bilat-occipital_rel',
 'gctx-bilat-occipital_per',
 'gctx-bilat-parietal_abs',
 'gctx-bilat-parietal_rel',
 'gctx-bilat-parietal_per',
 'gctx-bilat-temporal_abs',
 'gctx-bilat-temporal_rel',
 'gctx-bilat-temporal_per',
 ',anon_id,Unnamed: 1,Participant ID,Name,Surname,Nombre T1,AN_MRI,Date_MRI,Age at diagnostic visit (in years),Diagnostico Presuntivo,Age at death,Age at symptom onset,Sex,Education,APOE4 status,CSF amyloid positivity (yes/no),PET PiB amyloid positivity (yes/no),PET tau positivity (yes/no),FDG PET (hypometabolism profile),diag,unknown_abs,unknown_rel,unknown_per,left-cerebral-white-matter_abs,left-cerebral-white-matter_rel,left-cerebral-white-matter_per,left-cerebral-cortex_abs,left-cerebral-cortex_rel,left-cerebral-cortex_per,supratentorial_ventricles_abs,supratentorial_ventricles_rel,supratentorial_ventricles_per,left-cerebellum-white-matter_abs,left-cerebellum-white-matter_rel,left-cerebellum-white-matter_per,left-cerebellum-cortex_abs,left-cerebellum-cortex_rel,left-cerebellum-cortex_per,left-thalamus-proper*_abs,left-thalamus-proper*_rel,left-thalamus-proper*_per,left-caudate_abs,left-caudate_rel,left-caudate_per,left-putamen_abs,left-putamen_rel,left-putamen_per,left-pallidum_abs,left-pallidum_rel,left-pallidum_per,4th-ventricle_abs,4th-ventricle_rel,4th-ventricle_per,brain-stem_abs,brain-stem_rel,brain-stem_per,left-hippocampus_abs,left-hippocampus_rel,left-hippocampus_per,left-amygdala_abs,left-amygdala_rel,left-amygdala_per,csf-freesurfer_abs,csf-freesurfer_rel,csf-freesurfer_per,left-accumbens-area_abs,left-accumbens-area_rel,left-accumbens-area_per,left-ventraldc_abs,left-ventraldc_rel,left-ventraldc_per,right-cerebral-white-matter_abs,right-cerebral-white-matter_rel,right-cerebral-white-matter_per,right-cerebral-cortex_abs,right-cerebral-cortex_rel,right-cerebral-cortex_per,right-cerebellum-white-matter_abs,right-cerebellum-white-matter_rel,right-cerebellum-white-matter_per,right-cerebellum-cortex_abs,right-cerebellum-cortex_rel,right-cerebellum-cortex_per,right-thalamus-proper*_abs,right-thalamus-proper*_rel,right-thalamus-proper*_per,right-caudate_abs,right-caudate_rel,right-caudate_per,right-putamen_abs,right-putamen_rel,right-putamen_per,right-pallidum_abs,right-pallidum_rel,right-pallidum_per,right-hippocampus_abs,right-hippocampus_rel,right-hippocampus_per,right-amygdala_abs,right-amygdala_rel,right-amygdala_per,right-accumbens-area_abs,right-accumbens-area_rel,right-accumbens-area_per,right-ventraldc_abs,right-ventraldc_rel,right-ventraldc_per,corpus_callosum_abs,corpus_callosum_rel,corpus_callosum_per,ctx-lh-superior+transversetemporal_abs,ctx-lh-superior+transversetemporal_rel,ctx-lh-superior+transversetemporal_per,ctx-lh-cingulo_abs,ctx-lh-cingulo_rel,ctx-lh-cingulo_per,ctx-lh-frontalsuperiorandmiddle_abs,ctx-lh-frontalsuperiorandmiddle_rel,ctx-lh-frontalsuperiorandmiddle_per,ctx-lh-superiorparietal+postcentral_abs,ctx-lh-superiorparietal+postcentral_rel,ctx-lh-superiorparietal+postcentral_per,ctx-lh-inferiorparietal_abs,ctx-lh-inferiorparietal_rel,ctx-lh-inferiorparietal_per,ctx-lh-medialoccipital_abs,ctx-lh-medialoccipital_rel,ctx-lh-medialoccipital_per,ctx-lh-parahippocampal+fusiform+entorhinal_abs,ctx-lh-parahippocampal+fusiform+entorhinal_rel,ctx-lh-parahippocampal+fusiform+entorhinal_per,ctx-lh-middle+inferiortemporal+pole_abs,ctx-lh-middle+inferiortemporal+pole_rel,ctx-lh-middle+inferiortemporal+pole_per,ctx-lh-lateraloccipital_abs,ctx-lh-lateraloccipital_rel,ctx-lh-lateraloccipital_per,ctx-lh-orbitofrontal_abs,ctx-lh-orbitofrontal_rel,ctx-lh-orbitofrontal_per,ctx-lh-precentral+paracentral_abs,ctx-lh-precentral+paracentral_rel,ctx-lh-precentral+paracentral_per,ctx-lh-frontalinferior_abs,ctx-lh-frontalinferior_rel,ctx-lh-frontalinferior_per,ctx-lh-precuneus_abs,ctx-lh-precuneus_rel,ctx-lh-precuneus_per,ctx-lh-insula_abs,ctx-lh-insula_rel,ctx-lh-insula_per,ctx-rh-superior+transversetemporal_abs,ctx-rh-superior+transversetemporal_rel,ctx-rh-superior+transversetemporal_per,ctx-rh-cingulo_abs,ctx-rh-cingulo_rel,ctx-rh-cingulo_per,ctx-rh-frontalsuperiorandmiddle_abs,ctx-rh-frontalsuperiorandmiddle_rel,ctx-rh-frontalsuperiorandmiddle_per,ctx-rh-superiorparietal+postcentral_abs,ctx-rh-superiorparietal+postcentral_rel,ctx-rh-superiorparietal+postcentral_per,ctx-rh-inferiorparietal_abs,ctx-rh-inferiorparietal_rel,ctx-rh-inferiorparietal_per,ctx-rh-medialoccipital_abs,ctx-rh-medialoccipital_rel,ctx-rh-medialoccipital_per,ctx-rh-parahippocampal+fusiform+entorhinal_abs,ctx-rh-parahippocampal+fusiform+entorhinal_rel,ctx-rh-parahippocampal+fusiform+entorhinal_per,ctx-rh-middle+inferiortemporal+pole_abs,ctx-rh-middle+inferiortemporal+pole_rel,ctx-rh-middle+inferiortemporal+pole_per,ctx-rh-lateraloccipital_abs,ctx-rh-lateraloccipital_rel,ctx-rh-lateraloccipital_per,ctx-rh-orbitofrontal_abs,ctx-rh-orbitofrontal_rel,ctx-rh-orbitofrontal_per,ctx-rh-precentral+paracentral_abs,ctx-rh-precentral+paracentral_rel,ctx-rh-precentral+paracentral_per,ctx-rh-frontalinferior_abs,ctx-rh-frontalinferior_rel,ctx-rh-frontalinferior_per,ctx-rh-precuneus_abs,ctx-rh-precuneus_rel,ctx-rh-precuneus_per,ctx-rh-insula_abs,ctx-rh-insula_rel,ctx-rh-insula_per,brain_abs,brain_rel,brain_per,wm_abs,wm_rel,wm_per,gm_abs,gm_rel,gm_per,csf_abs,csf_rel,csf_per,cerebellum_abs,cerebellum_rel,cerebellum_per,bpf_abs,bpf_rel,bpf_per,evans_abs,evans_rel,evans_per,gctx-lh-frontal_abs,gctx-lh-frontal_rel,gctx-lh-frontal_per,gctx-lh-insula_abs,gctx-lh-insula_rel,gctx-lh-insula_per,gctx-lh-occipital_abs,gctx-lh-occipital_rel,gctx-lh-occipital_per,gctx-lh-parietal_abs,gctx-lh-parietal_rel,gctx-lh-parietal_per,gctx-lh-temporal_abs,gctx-lh-temporal_rel,gctx-lh-temporal_per,gctx-rh-frontal_abs,gctx-rh-frontal_rel,gctx-rh-frontal_per,gctx-rh-insula_abs,gctx-rh-insula_rel,gctx-rh-insula_per,gctx-rh-occipital_abs,gctx-rh-occipital_rel,gctx-rh-occipital_per,gctx-rh-parietal_abs,gctx-rh-parietal_rel,gctx-rh-parietal_per,gctx-rh-temporal_abs,gctx-rh-temporal_rel,gctx-rh-temporal_per,gctx-bilat-frontal_abs,gctx-bilat-frontal_rel,gctx-bilat-frontal_per,gctx-bilat-insula_abs,gctx-bilat-insula_rel,gctx-bilat-insula_per,gctx-bilat-occipital_abs,gctx-bilat-occipital_rel,gctx-bilat-occipital_per,gctx-bilat-parietal_abs,gctx-bilat-parietal_rel,gctx-bilat-parietal_per,gctx-bilat-temporal_abs,gctx-bilat-temporal_rel,gctx-bilat-temporal_per',
 'pet_id']

In [96]:
fleni100 = fleni100_match[
    [
        "pet_id",
        "diag",
        "CSF amyloid positivity (yes/no)",
        "PET PiB amyloid positivity (yes/no)",
    ]
]
fleni100 = fleni100[fleni100["pet_id"] != "-"]

In [97]:
fleni100["CSF amyloid positivity (yes/no)"].value_counts()

CSF amyloid positivity (yes/no)
Yes          15
Normal        8
Sin Datos     1
Name: count, dtype: int64

In [98]:
fleni100["CSF"] = fleni100["CSF amyloid positivity (yes/no)"] == "Yes"

In [99]:
fleni100["PET PiB amyloid positivity (yes/no)"].value_counts()

PET PiB amyloid positivity (yes/no)
Yes    65
No     51
Name: count, dtype: int64

In [100]:
fleni100["PET PiB"] = fleni100["PET PiB amyloid positivity (yes/no)"] == "Yes"

In [101]:

# correlation between "diag", "csf" and "pet pib"
fleni100[
    [
        "diag",
        "CSF",
        "PET PiB",
    ]
].corr()

             diag       CSF   PET PiB
diag     1.000000  0.298516  0.870780
CSF      0.298516  1.000000  0.003642
PET PiB  0.870780  0.003642  1.000000

In [102]:
fleni100

,pet_id,diag,CSF amyloid positivity (yes/no),PET PiB amyloid positivity (yes/no),CSF,PET PiB
0,b87479c8-641ec909-8b8effc1-9b58a18a-573f8414,1.0,Yes,No,True,False
2,e5a4f8b8-f6ad7d45-52b4b6e8-f3ebf6cd-c8e8f25b,1.0,NaN,Yes,False,True
3,c96cbd4d-f9cfda98-8bd71bc1-e26e87e3-e25c6d50,1.0,NaN,Yes,False,True
4,b172e084-61708876-5cb503da-b65f4f85-e1c4e110,1.0,Yes,Yes,True,True
6,ad80ea14-f27dad6f-3e12c1f0-2993bcc3-4cb99a80,0.0,NaN,No,False,False
...,...,...,...,...,...,...
225,a4dc5f48-55b6fe7b-95df4cc2-d1a9765f-acf114ce,1.0,NaN,Yes,False,True
226,24fa2c1d-1218de8c-c96d25cb-28e77c7a-89e0c0a4,1.0,NaN,Yes,False,True
231,1541a4b6-f7f308c1-9e017a0a-d247bc16-e3117067,1.0,NaN,Yes,False,True
232,5e28bc57-30e1abd2-a0a7d856-4fc1af1e-5bee10d2,1.0,Yes,No,True,False
233,625ddb3f-6b6adb4a-0653c1b1-1e566cc8-3fe2fab5,1.0,NaN,Yes,False,True

In [103]:
!pip install -U openpyxl

Requirement already satisfied: openpyxl in /Users/nacho/opt/anaconda3/envs/pet/lib/python3.12/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /Users/nacho/opt/anaconda3/envs/pet/lib/python3.12/site-packages (from openpyxl) (2.0.0)

In [104]:
fleni600_og = pd.read_excel(
    "~/Downloads/Fleni/fleni600/fleni600_original.xlsx",
)
fleni600_og

,Unnamed: 0,StudyDate,anon_id,PatientID,PatientSex,PatientName,Conclusion,Diagnóstico
0,238,20200825,625ddb3f-6b6adb4a-0653c1b1-1e566cc8-3fe2fab5,702774,M,WANGER^WALTER ROBERTO,-ALa distribución espacial de los hallazgos ...,AD
1,234,20201006,c45568f2-c860c13b-ddabe3eb-7bc72f65-dc96ba33,701575,F,RUBIO^MARIA ALEJANDRA,-ALa distribución espacial de los hallazgos ...,AD
2,435,20190426,b0e1b100-f29d020b-07fb9c16-bb41abdc-43d7b0e8,597445,F,BRALO^ALICIA ESTER,-ALa distribución espacial de los hallazgos ...,AD
3,247,20200804,ee1769c5-189b12d7-187a454e-f13189f4-19f82052,554900,M,LOBOS^ANIBAL PEDRO,Amiloidosis cortical difusa en el presente e...,AD
4,387,20190718,ec84b311-4f89bd80-bfd691ed-bb1cd2f4-c700b95c,655037,F,SANCHEZ^MARCELA ADRIANA,Amiloidosis cortical difusa en el presente e...,AD
...,...,...,...,...,...,...,...,...
1610,1610,20130215,394f9c0f-407407df-924d39d5-385898a0-103e5c19,474496,M,RIVAROLA^HUGO EUGENIO,NaN,NaN
1611,1611,20130221,2137659d-aa1d903d-beb5a549-8d252a72-a903e6a2,266991,F,BER^PATRICIA,NaN,NaN
1612,1612,20130227,291a10ba-ca622d77-7eb09271-f0948eeb-745ef704,475954,M,GALOSI JUAN CARLOS,NaN,NaN
1613,1613,20130205,667cb287-d9eee39e-e4a18254-beebf4c8-52aa0723,188881,F,VENANCIO^MARIA ALEJANDRA,NaN,NaN
1614,1614,20130123,419fb7ba-a7646e04-81c8b19d-ac69325b-95b07fef,469780,F,MARTIN^MARIA LUISA,NaN,NaN

In [105]:
# fleni600 = fleni600_og[
#     [
#         "anon_id",
#         "Diagnóstico",
#     ]
# ]

fleni600 = fleni600_og

fleni600 = fleni600[fleni600["Diagnóstico"].notna()]
fleni600 = fleni600.rename(
    columns={
        "anon_id": "pet_id",
        "Diagnóstico": "diag",
    }
)

fleni600

,Unnamed: 0,StudyDate,pet_id,PatientID,PatientSex,PatientName,Conclusion,diag
0,238,20200825,625ddb3f-6b6adb4a-0653c1b1-1e566cc8-3fe2fab5,702774,M,WANGER^WALTER ROBERTO,-ALa distribución espacial de los hallazgos ...,AD
1,234,20201006,c45568f2-c860c13b-ddabe3eb-7bc72f65-dc96ba33,701575,F,RUBIO^MARIA ALEJANDRA,-ALa distribución espacial de los hallazgos ...,AD
2,435,20190426,b0e1b100-f29d020b-07fb9c16-bb41abdc-43d7b0e8,597445,F,BRALO^ALICIA ESTER,-ALa distribución espacial de los hallazgos ...,AD
3,247,20200804,ee1769c5-189b12d7-187a454e-f13189f4-19f82052,554900,M,LOBOS^ANIBAL PEDRO,Amiloidosis cortical difusa en el presente e...,AD
4,387,20190718,ec84b311-4f89bd80-bfd691ed-bb1cd2f4-c700b95c,655037,F,SANCHEZ^MARCELA ADRIANA,Amiloidosis cortical difusa en el presente e...,AD
...,...,...,...,...,...,...,...,...
633,165,20210923,55e4e05f-63d7f972-8268b162-88e10c2f-b357b9d5,716430,M,ANTOLIN^ELEODORO JORGE,"La ausencia de PIB en corteza cerebral, al mo...",non-AD
634,167,20210920,3e933062-0cb72fab-bcea413b-79beaa2d-f216915e,735946,F,LEJTMAN^BERTA LILIANA,"La ausencia de PIB en corteza cerebral, al mo...",non-AD
635,205,20210111,e8c79ba5-6d9dbbda-ee35f81a-fb297bc9-bd605906,702579,M,PARDO^SILVERIO,"La ausencia de PIB en corteza cerebral, al mo...",non-AD
636,926,20150915,efbf3dab-14c5c80e-55f0f93d-482237a0-9acc8e1f,212192,M,SACK^AUGUSTO,La ausencia de retención de amiloide disminuy...,non-AD
637,951,20150915,7fb34c5b-122c2b29-27c260a3-d6351b3c-ffddfa6c,212192,M,SACK^AUGUSTO,La ausencia de retención de amiloide disminuy...,non-AD

In [106]:
import os
import glob

In [107]:
fleni100_nifti_files_dir = "~/Downloads/Fleni/fleni100/entelai-fleni-pet-base-diferencial/panania/Neuro/fleni_pet_en_base_dif/fleni100/"

fleni100_nifti_files = os.listdir(
    os.path.expanduser(fleni100_nifti_files_dir)
)

fleni100_nifti_files_ids = [
    os.path.splitext(os.path.splitext(os.path.basename(f))[0])[0] for f in fleni100_nifti_files
]

fleni100_nifti_files_ids = set(fleni100_nifti_files_ids)

fleni100_ids = set(fleni100["pet_id"].values)

len(fleni100_nifti_files_ids), len(fleni100_ids), len(fleni100_nifti_files_ids.intersection(fleni100_ids))

(115, 115, 115)

In [108]:
fleni600_nifti_files_dir = "~/Downloads/Fleni/fleni600/converted_niftis/"
fleni600_nifti_files = os.listdir(
    os.path.expanduser(fleni600_nifti_files_dir)
)
fleni600_nifti_files_ids = [
    os.path.splitext(os.path.splitext(os.path.basename(f))[0])[0].split("_")[1] for f in
    fleni600_nifti_files
]

fleni600_nifti_files_ids = set(fleni600_nifti_files_ids)
fleni600_ids = set(fleni600["pet_id"].astype(str).values)
# len(fleni600_nifti_files_ids), len(fleni600_ids), len(fleni600_nifti_files_ids.intersection(fleni600_ids))

In [109]:
# list contents of zips

import zipfile

def list_zip_contents(zip_path):
    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
        return zip_ref.namelist()

fleni600_zip_path = "~/Downloads/Fleni/fleni600/"

fleni600_zips = glob.glob(os.path.expanduser(fleni600_zip_path + "*.zip"))

zips_n_contents = {
    zip_file.split("/")[-1].split(".")[0]: (
        list({file.split("/")[0] for file in list_zip_contents(zip_file)})[0]
    ).split("Anonymized")[1]
    for zip_file in fleni600_zips
}

# bi directional mapping
file2id = {
    file: id_ for id_, file in zips_n_contents.items()
}

In [110]:
zips_n_contents

{'06dbf910-de873462-8d4f145e-06ed168b-84f1db1b': '1010',
 '9bd347a9-7390ce38-7858ffa3-b953e50c-602ca9c0': '562',
 'e1554ec6-338ebdbb-f55dfa4f-d84b87c9-ed5a22c6': '669',
 '34df6676-5670b64e-9d17e380-dca30921-e522d0d5': '1324',
 '9bd68ca9-a86cecf0-0f4b6910-55e449b4-a5740284': '654',
 'd89acb49-fdcbf1f7-9c244597-b0030755-56b15c45': '1233',
 '6eed0b1d-6fb9e768-dca6a632-340b8cf3-2cfcbec5': '504',
 '64122245-5f6ddf0e-e3dc9646-7dde4fd6-0fcda932': '1767',
 '4a9d2af0-ccbd9500-2e680ae7-bdcb898e-4b18f321': '923',
 '33027036-5c1b9e3b-eba9b201-1e94900f-a35bdf50': '1290',
 '852f330a-1bc32934-5a7055bc-09d37959-fb9ff5ee': '709',
 '00f0d649-7c3c519a-724d9e2b-f6a90361-7ed8e91f': '662',
 '45eaa40b-6d19c96a-1ff33292-f9651914-386a9104': '589',
 '38b0afbf-b3f9f98e-7d99a144-be80caed-a457f7c3': '396',
 'e0f89eea-4c053a9d-71c0e76a-e0438014-90dde32c': '218',
 '9160bb66-bff1151d-dcaf52bf-95fd9015-fc379184': '1616',
 'e53a9958-547341d7-eec154b3-1191495f-c4e6ff1b': '1140',
 'bf18ccf8-e703975a-7e41c367-d6579604-6483a1d4': '1412',
 '4b2f339a-85927c6e-441d146b-f9ba37cb-1306af70': '1276',
 'f2251653-53afe4c3-e390d415-4c704ae2-3d0d3cb0': '911',
 'bccd8be9-dc29cb58-2fe06c1a-a46a85d0-8edc4cb3': '946',
 '4b2bcc7a-3d1e87d1-fcf7ecf3-699fc4eb-5eba3f1a': '1726',
 '47691f6c-5b59d434-0aad72b4-8b1e5a52-1a31ebbb': '1535',
 '6ff62503-04601df7-1104f334-d26ebc91-a37f2c34': '1550',
 '33b7cbaa-76646fe4-3b1da249-c6b8ac17-c7967cf8': '1022',
 'e71e9bde-ec3e80e2-df2a795a-688f45a9-c4813443': '1626',
 'bc08a8aa-0a3a0516-70581584-39d0206c-659480ae': '769',
 'e8e36663-b29b20eb-36cd48e0-9cc7996e-4883c9ea': '1050',
 '368a5318-1a4e6864-a3cd4e0c-3bf79ae6-aa58b662': '1595',
 '27bfb8ae-0f5bc8a7-86dc760c-fb9f9f04-3e9c0d22': '1717',
 '092768a8-29e55f2a-840a0fa4-7d2143a8-589ac90d': '593',
 'abf8491a-d1c051fa-4a82b92a-454c7898-a8b5f8d1': '644',
 '8dbcc506-88d665aa-758f8bf0-c86ca2be-358eff37': '963',
 'ab3308a4-8d085219-ad7ea17e-480846b5-bc5f2981': '819',
 '84626eff-8b540588-5086326d-320d1ad3-91ed3792': '1519',
 'a393e3fa-56095165-eb554350-cf744b58-ca5028e0': '192',
 'b5c3083c-492d4520-f926cbe8-6da6f12f-c9413b9a': '1473',
 '3f3c0b5a-e6630b26-53079866-423b2546-b61f03e4': '998',
 '267b86fb-64c2754d-00020126-60d16ff0-98efe3ff': '191',
 'fa23ac67-a5f39449-280e3aac-a77160af-53c1b9f7': '777',
 'be4c565b-eff4aa0e-aedb1e71-f4ed88ca-96f05b10': '825',
 '8849a85a-68481d1a-846af63f-975aca00-513fdd83': '513',
 'a6a60ba2-63551bd0-ab1f9bd2-262b6408-4ea8080e': '207',
 'eb600c81-17c4df39-d7e90a5c-ec587f9a-950d208b': '918',
 '2dd965ed-78a51137-33e1ea33-1016be50-0dbda07f': '307',
 'd2995db1-9d6fec74-df2b5f36-758bca99-d55f41bb': '1482',
 'f7c17fd7-5751471c-0a13c4e1-03af9c4d-fd104ac6': '1299',
 'a0b31432-9cb34f61-fd2ba0c8-189b4d5c-e8b8abc1': '741',
 '9dcb1da5-a5423f01-41cda63a-1dd28e47-ca841f54': '801',
 '7610266b-ca235fd1-d02b147f-e658c7e4-ac52c728': '656',
 'bbf8c138-051bfe56-fec5f467-ddf026b3-0b0aadad': '310',
 '6c5d9e01-9955ba75-659c0d91-6db3ab63-4d7adc92': '927',
 '587e1d81-962a01be-660656df-73e37c6c-c64ad1b7': '372',
 '6e814edc-f77408ba-e739786a-d66288da-38fc1bc7': '949',
 '1b7dd223-3cca1e15-48fe53eb-ac68c9c4-4edf7593': '1332',
 '4de46e92-62422284-415e9063-c3d408b4-fa2bf1e7': '350',
 'da5f4fff-5095f0ae-cea36cfe-02f7a231-6c8a98e0': '1005',
 'f4d3f4b2-e6f19b7a-bcba548c-a9c9842d-b7ffbd0b': '1533',
 'a1e397e6-76ae7134-a1b087bd-df002cb4-26d01138': '533',
 '66e47a34-038b3685-e0d112f2-860137fc-6421f3e1': '880',
 'b11afeea-5674a7bb-19710294-f72abee9-779f6b97': '538',
 '3981105a-cbbb282c-d0baafe8-f21de654-9aa3a9e4': '1465',
 'f2df5678-09a233da-3c24f8e5-e128dcf9-0823c883': '1702',
 '054cb8e0-98ae6171-2a227a59-850dc384-a7b06c85': '566',
 '4c87e3fc-9f8b1cc5-ec2c398f-fe9ab4ed-edcad99a': '821',
 'c6232b0a-6ed5e249-6d7ff895-182277ae-d5af0cff': '1063',
 '409fd369-72cad27c-cd7bb5c1-1644baa9-93a3c4b0': '1762',
 'ae52839f-71db02c9-dcf47606-e9824f11-673f5cd4': '1459',
 'd84c77df-b19570f9-24c0e7d7-6ca3698b-88f1e52c': '329',
 '61fad5c6-668de0b5-0dc0ca38-fb301c1f-f844e42d': '734',
 'dd860e6a-2003e499-ab87151e-7e30cfa4-e318f42d': '1292',
 '197f8978-e75ada22-082a0fd1-33b6450f-7b74766b': '1399',
 '86217a99-85619185-6a84c88b-be5bba17-2ee4d32d': '348',
 'b9076c8c-0109ac9e-57274290-45bca4bd-2d59f40e': '823',
 '96e0f53f-17f98ef2-056176a6-0269d93e-0b4f334e': '1230',
 '867aa61f-59e393e4-ea55df7c-4870afe7-ef65d57c': '590',
 '3e933062-0cb72fab-bcea413b-79beaa2d-f216915e': '328',
 '4e1ae26b-14869d0b-2f6438fa-a294c86f-cceeeaaf': '1419',
 'b67a0174-3a5e2c8a-a7ef9283-5dadf41c-cd41056c': '570',
 '298801b7-ab81f6a0-0703b0a0-0add9ede-bd42f3a0': '944',
 '4553611b-14b3e6a0-45ea463a-5cc4d855-00654b07': '343',
 '9b5add71-b4c29c77-c8c30a03-2f49771f-a31b45ff': '1175',
 '6bff0373-3784fe78-09b9df31-b7652e5f-cd119a62': '198',
 'ee1769c5-189b12d7-187a454e-f13189f4-19f82052': '408',
 'd6bbe37d-0679d1ed-59fa1160-6d6d71d9-cabf73b2': '1435',
 '1eed16d8-e959ea95-474a15c2-77aaa494-303d4d17': '1725',
 '21bee239-226d7b3d-4a4e699f-dc499878-67997d15': '1126',
 '44a28d4d-715fb1d1-a27b6b74-8453221e-971636d2': '166',
 '30014fb7-045e3540-c8cd396c-7f653572-b851b829': '1386',
 'fccc4b25-6ac728a9-6d0fc4d4-63144f82-d12a6fb4': '1318',
 '9793f12d-80c566d2-b39a1a66-3a354507-fc37ecdc': '1007',
 'f25e8e4d-a80e9f9b-a7d14884-02594a7d-d5496f72': '323',
 'd774ee4e-cb8ade00-d34d5dc7-29878d4e-eadf38b7': '683',
 '2e8ef824-29b8fe5d-4a4c8446-065ce060-7d159f5d': '1040',
 '015eb5c9-31cf95d7-d19495f0-990442a9-52d4b6b0': '739',
 '96be73d4-3f44b129-bd2270e1-fd971e38-27ee1dfc': '433',
 '8e12c683-e48c0092-779fd1b3-5e7bc494-7e227a95': '337',
 'cb2881a0-6b7c740f-81d3c742-c9307dfe-89fb6f44': '866',
 'd997768a-f47363a7-ff81b1db-bb187c51-3145d2b0': '684',
 '02d5ee83-c3b0fb53-368826a5-5f69a6f2-d4d5bdbc': '885',
 'ff891e58-3a7eec4d-9a3897fe-1de6db9d-5c988f77': '615',
 '22e42fbe-2f5e8375-337266d7-9610b183-a923614e': '480',
 '9a9fdbb3-1346ed62-f6201e73-cab5b89b-728b2400': '704',
 '089d384c-ee81b966-63de481f-b818da02-988568fe': '697',
 '7b2563e2-796b12c0-5ca8a153-17618566-6da77739': '221',
 '44c7f59a-206ec1b0-dd5f19fa-dc5372c8-18292bac': '1238',
 '3666ee86-16e754ac-eab6e6d2-4b0ed1a8-52504d30': '617',
 '79d4d154-6d2f7c22-1d08f900-61553d08-c7c32819': '1679',
 '17323508-ce40ae57-8c616468-9909663d-eff493d2': '1082',
 '4bb11e84-e7892094-557e839e-77bdd97d-5e1fe4ea': '1759',
 '11b3d5a0-08aadacd-d773d5d7-9f251461-70f6740d': '1541',
 '218a0c08-8d9e7d76-283a01e8-5c244cb7-95c3eb6c': '487',
 '427bf2d0-eed4925a-8a094d07-93f5e700-8da3bc5b': '1032',
 '37bd3c0f-c8a1bd1b-294ac32d-5f16b7fd-34faad5d': '780',
 'ec78872c-5897c5a5-739813bd-218dac09-9ed9a352': '183',
 '8e67cb50-292f9ea1-9737d5c1-60375ce6-d0301c93': '1350',
 '9b54d992-52acb96c-aee40f18-797d7551-ce0eccc3': '871',
 '996d4331-82f70f4e-f3f6476f-b91d3f13-b9baf9ae': '1761',
 'edbbfc2c-2a2cbd05-9829252b-a3165a81-9c8e9efe': '1164',
 '339a7cba-3c54e0d7-ef8ff258-441e3d92-a934491c': '1466',
 '403afd2f-18290107-33dbfea0-293697df-4b1d33da': '442',
 '2febe34c-406e522d-9d08417c-0c2040c9-ca136b04': '725',
 'c58b3098-96692f31-a8cf3957-0c775be3-ced72325': '1729',
 '66c6ca15-563339a8-8e16fbc0-636b507d-6a33a7cf': '672',
 'e733fe57-343936b1-5f470fb7-725f5e0d-fb2d81bb': '1714',
 'd340fa9b-d4fd2015-f9d93b4e-60926b0c-b5af4795': '718',
 'c11146df-85fe4ed6-7d99a1da-48ca9e45-fc963cfc': '807',
 '10043fc6-bef278fa-2836658b-170c217f-fb0e78f3': '665',
 '9af87346-e7f0b72e-33f95c57-6024992b-aea7d0eb': '1272',
 '4d05248c-f24aab8e-80fcefa2-6acdeb29-6bd0299c': '541',
 '9e5870dc-a072db77-8df0fd85-7725fafb-ffb0a340': '1153',
 'eb06bfba-6aa1d33a-8abcf7af-459a2f4e-6b21cd87': '1527',
 '6679c9ac-ff5b3eee-73520f1e-adf11e7d-4d331dfe': '164',
 '00d2050f-75c4d6d7-225be54b-84be5e5e-64411382': '379',
 '99af4b63-63f42167-8151ee3e-82024743-f5a2d57a': '1195',
 'bb1647b2-6168d5ea-3939f6fa-167b41ea-fa0575d8': '215',
 '9980cbc2-7db22fd3-756001cd-b8a5b017-9a8c6dc4': '1513',
 '28746722-2936ff66-9d412187-a319fe83-7e8159ab': '737',
 '37b54328-91f5a3cb-d6c22e88-b6ea5e16-c98966e7': '1152',
 'e948df86-6102ed09-c2af4b7a-236ac364-949b9756': '755',
 '4f9d582a-c992d94b-6418c65a-8866c929-7a52d395': '1039',
 '0cfd868a-c1f44af9-e9004851-7c67bd3c-30dd8c43': '790',
 '6aa29532-3b8308ab-29cb8dcb-b945bbe7-6ac9fb82': '1407',
 '620091f4-d7a76ed2-fd23a402-27646f96-83ee8337': '693',
 '43922aed-313be8c4-588e103d-3a0c046b-2ffccf39': '520',
 '3656419d-1523529f-f080cc08-ac5fbbf1-441422c8': '1185',
 '56a4e21c-5c1417af-6abd963a-0bc99fb7-d809a93e': '1393',
 '9b53a850-50a65b98-373f6fe7-5906ed09-a449a43c': '948',
 '2fc787e7-33b59033-aeb7e765-ee7afe60-c4f17aa3': '435',
 'df9d4a11-f8ed5e18-ec1e9e2a-43a0e204-937c3327': '1265',
 'd5385b6a-d3a569c4-263d8648-14a29c41-23d0da4f': '1117',
 '0528ee18-bd9a1b50-c0dec226-384eed35-341a81c1': '1645',
 '2f9e57cf-19dd0ee8-c7c2e09a-79271eb5-f64fc781': '794',
 '6c656abe-12fa280d-5fef7a26-5d4964d9-6bf40ec3': '1452',
 '8e2ac118-83717c3f-07cc8d0e-1a1516f5-9c06ba0a': '1322',
 '5e1396ef-1a3ad447-9d4ce7f5-6e5ee6eb-d9c90343': '1649',
 '213a67df-036236fb-c1837d49-089678a9-0d7cbb1b': '1560',
 'd23f501b-9f497f7e-bf745487-cc353987-33ff7a5c': '822',
 'c8e28ce1-b2d94170-8c5d5957-ee8fa58c-f33c6875': '1062',
 '95ceb1b8-5be7722a-2efdde95-f0c0e27e-1ac5b08b': '1621',
 '699a54ce-60d2b6d0-a986e38b-af4d2f11-eebbf8ca': '558',
 '52b3eaf8-2ead1702-a717490c-2eb2e329-5de739b4': '786',
 '6fdfb111-99431e7b-c05f0bda-4d1acb7e-88c8f8f8': '1334',
 '95a6ee94-e07c3d16-5d354c84-cd6ab4a4-d0ee04e3': '1700',
 '83400e5d-6f5ad608-c96e7ed8-b6762a8c-8bee2ae2': '1319',
 '37f351a7-db70219d-d966e00c-867d9e4c-bc81a66f': '724',
 '06509c01-b52e7de6-a0755e96-9b574935-cea8af70': '1376',
 'd5e797f6-384053b0-deea9356-2125f6f0-44c13808': '1257',
 '11032733-26492d86-4fdeecc3-cba8a55e-4cc7687b': '420',
 'd3ef053b-fc3583c4-ea572369-c703358b-4d714ca4': '406',
 '1ecd8590-a4b58359-30292d24-bc850d05-39d0d4e9': '975',
 'ec84b311-4f89bd80-bfd691ed-bb1cd2f4-c700b95c': '548',
 '4316e9f1-a1fca3bc-578a7f99-ecd1d690-2b981969': '1263',
 'a58842c3-2665d0f8-65c9d0f8-9c6020c7-133daa35': '1377',
 '60fd9e20-0c5de7e5-1a4486e0-9970ec58-d3881e7d': '1255',
 '38bb3ae3-74bc478c-bfabf1d2-09e41e1b-7c75ff40': '1348',
 '951f732e-825f0770-0017eec3-826fbc12-95486a8b': '1149',
 '4e3f4548-c4afb332-f3f8d2ca-5d86602f-89f26f99': '1086',
 '0a15351a-1c94e3c3-545b0f91-9afeca42-7d3e1cac': '429',
 '3e2e59d3-a182cdd1-c9e112e2-cb23c4cd-b7ed6cc1': '517',
 '166e491c-cd824e7b-31deb77e-58c41c5c-6ca420db': '612',
 'ae9b540d-60191f17-3e3a1f1a-b21bc6ef-d2ceb6ea': '1252',
 '164751e1-d6db08f6-8eea8b79-a2ef609c-362a8321': '248',
 'b44d8b91-7f8d2d29-c04a63a5-e5b8f087-dbcaec1d': '563',
 '97ed3098-0ffb7f4e-8398f4b0-71ae3079-e5c1d3d9': '1293',
 '51766a8c-931608ef-0863171e-6d9d0cfb-e2f22214': '1657',
 'a2a42680-e0608ab1-2a69fe41-032598e6-1b350022': '225',
 '5a6700b2-974ebbd9-980ef4a6-3bdc7abc-500acf3f': '500',
 'd851c679-a021649a-0cd72149-2ed38775-1486eaf0': '1135',
 '6357065f-55d036be-03e1d8ba-b0dc8505-c4d562c6': '935',
 '76d7b2a3-99602baa-32b0f82b-22b6cd5f-6f9a6391': '640',
 'ae4130ac-1c57b6ba-1087205e-75147ea8-2827e002': '529',
 'b8886e1f-bddc37c7-4fd67ab6-281cd219-4c8fc2bc': '1489',
 '70976df6-8bf40b38-8433bcab-b442dd28-3067e49f': '526',
 'fb14ef5d-3a5e0205-e5043d31-c95388d5-d268c744': '1440',
 '40758145-715ae0bf-fbde6208-370e5c69-33166290': '1748',
 '1bde6ab5-7509f442-2ec69d48-d3699783-24d04228': '1507',
 'bb0cf8af-40de6dcb-41907224-c36645c9-88795f5b': '1209',
 '50f2ec2a-85595e1f-0cfacf8d-5bc4fdd7-9b2ff3c9': '292',
 'cfdab662-d07df354-7faa8480-5f62d062-e621720c': '1744',
 'a10539e5-b7980ddd-335d9702-dbbb8585-a323a6a2': '1053',
 'ef4fe077-de0ddf93-49e581eb-dcf97cc4-3530b6f6': '1343',
 'a2e304d1-2514af76-ecc94dba-b02dc2f0-dab26cfe': '670',
 'b42c105c-4d79cfe9-48687e06-c7f54db5-322e43c5': '839',
 '1dc4ba46-70c10999-04b3c2df-159bbfbb-78581e9d': '470',
 '08a041c8-97937962-cd837337-915194de-2867a287': '1236',
 '92dab6c7-d128b001-5b24c76d-0076144e-4cdeadc8': '1633',
 'eb196f49-e0565d25-87da8a2e-1ec37bc0-611baf58': '1471',
 '8d401a9b-59539a96-42feeeb5-d974a3ec-bae581f2': '1172',
 '016c4716-a6c535d6-35680437-01e476ef-116d732e': '1722',
 'a174b6e3-732267ea-15cb7b70-06bcedf6-aaff4f51': '1624',
 '1e10f627-7db18f5d-ce6b3364-ef86c8fa-61012f5d': '1701',
 '382afc28-eda672a4-7a4f5c5e-cad16603-5360b95e': '1632',
 '4d3647c4-ec43e4da-9ac736e1-93f4e3f4-ad1ff84e': '197',
 '4d520c94-7c68806f-c604a1fc-9678cd29-3216a33a': '368',
 '77ae1182-a7669060-7a7119ac-8aea04f6-d92fef2f': '557',
 '9f4788af-320c1f28-6a30ca7b-a7bc2318-4341b6e1': '1151',
 '23698a3b-71e234ac-db7ced18-262c0eee-bef83ae8': '243',
 '5e28bc57-30e1abd2-a0a7d856-4fc1af1e-5bee10d2': '391',
 'df197ff2-850f98d6-b2387220-e73af43c-4608190c': '161',
 'aaa749a8-1530bfb2-c2b8703d-fe731dd0-d9b7fda9': '1397',
 '39083e0f-e59eb98f-a8ff93a9-1ff0d24b-9cba986d': '893',
 'aca91b0c-f88649a2-1f20d111-352aac5f-92ba99e0': '1554',
 '1541a4b6-f7f308c1-9e017a0a-d247bc16-e3117067': '412',
 'd418a5d9-d6127db5-65fd4baf-1747ca06-b9d36205': '452',
 '1ac424ef-10a55f7f-7217fad9-76caca35-3f2367ea': '469',
 'f2a04bcb-85195f0f-9f0d8090-8ed66f9e-9201f3e8': '1186',
 '7892316c-4de11d73-74c2b0d2-e12848ad-833929c6': '1206',
 'f9b3c587-eeec9240-8e511516-bd5a2813-d3d9a91a': '1590',
 'a0466e65-966103ab-41395148-39837993-43240887': '1356',
 '77b3f2cd-756cfa0e-38f4c192-640409f5-a43d7a00': '345',
 '46de32dc-304ace87-3e5d90ec-40c915c5-91080284': '1488',
 '870ce879-8a24a6ed-afb7c8a0-02dd2d45-050d84c1': '1118',
 '3dfac0ba-8df9965d-4e8dd9b0-a488def5-d6fe5585': '1439',
 '2f3b013e-07886489-2c70ff78-76a2e8cd-6920fd8d': '1037',
 '3d8d5cd6-e2d3aa59-944b4be2-267e0366-5dff90d0': '1326',
 '83f4bb05-3997aa87-b05aa201-c4dc5c0f-77825f68': '648',
 '31de2f3e-39f0d82a-6cdd2b60-285f3321-688982de': '1453',
 '4f812c6a-11cd7d10-ed0d2d48-02879dec-2f98d5d0': '591',
 '842318b1-6c526f5b-2d39bcea-eac23505-df3ddf37': '620',
 '5f66b5f6-a5b5e4c5-7e397de4-1da1e37f-6eb45e96': '1017',
 'f5491bc8-aff8bd50-262b248e-fa7a8fbc-21650cf5': '205',
 'c91297e0-8e2ad563-42ee0d0e-951dad46-45542c17': '580',
 '6f141ea9-abc80bd7-869b724d-c5aebd6e-37d875aa': '322',
 '8efc9cea-d38794e4-5deaf408-4fdd2693-4f4c7dae': '740',
 'eefdef6e-ebad18f0-7d4f25d8-ce10dd08-39e00700': '1400',
 '99272cce-314ebb68-7ccda51e-f9e86ce7-f6e592dd': '1127',
 '442f77bd-04b8f791-ff1d55f6-b7c40938-f1ff4403': '347',
 '73401c3f-7d76024c-2b5af59c-dda3c81f-99372ea3': '1171',
 '965b0e30-7c207604-f9bd3831-f51f7c41-bcdd3a49': '1562',
 'b7a8affd-d43002f9-fda28d6f-75f393d4-ae22e4cb': '1563',
 '7d0939f5-bf036d18-c7aa15a2-6baad930-91ab9a3c': '908',
 '0af49fe7-36aea609-c3238542-9305e3b3-5606c349': '876',
 '03a528bc-b97aa2d5-0756cfc0-1dc94a07-094d49a0': '444',
 '06475e5d-0e983e29-638c580e-58ee5a1e-d9250ba5': '522',
 '4d837680-a00ddaa5-11e47c28-5756fd5a-8eb63ca0': '1361',
 '6d955f3c-d72106fa-9acfcafa-9788d41b-95a19124': '162',
 'f34fd8af-c1044ddc-6d2bd6aa-77732cd4-462e6c8e': '224',
 '7bea5db5-e419ce3d-d25383f3-5c893df7-5acfdc55': '405',
 'e785e1ae-4cc6f186-7984308a-d879a1f0-bcd90f94': '1162',
 '84617c12-f019a71d-e60ef99f-40991a4d-eb1ec2a6': '1092',
 'b2f35ad4-4bde53bf-d88b402a-c4c98d1b-60b7154f': '305',
 '8a2879ba-8f5c49c5-39ae1b13-080d505b-c1ccbb25': '1690',
 'ca38005e-dcc07bad-c1d9b17a-a40ca712-437d0fed': '951',
 '19d44fc4-c57c6fc8-d36493d4-84ffceeb-d6919dde': '172',
 'bbfad98e-08d00daa-a9f6410a-143e0cf0-a992d206': '581',
 '1daa3b47-4a094f1e-541cffb2-320c4d5a-1f7f9367': '193',
 '2b64ca46-ce632433-25311539-9422211c-35405899': '505',
 '221a1b75-2088d3f7-458d0a6a-7f04e183-b34fd2f4': '290',
 'a3502cac-e288fded-cb02d222-61b3e3f4-35402df5': '528',
 '4e3cd110-7d87b968-94f0e706-4bb0c0ee-b063ee0f': '535',
 '20c90567-2ce159c5-abc80113-503ecca7-e24c9d6e': '552',
 '3aa18eb0-43ae540c-ca30594d-3b2cc125-5028af82': '203',
 'b45e52dd-1d890a59-72c0decc-4cbc0c85-cc8ffc6b': '1567',
 'c734b9ac-2466c26c-5f03c5b7-7f070f49-ef79f88c': '945',
 'e2940d51-e00b3964-6d225936-895c44ab-bdfd22ab': '450',
 '2c2d93f7-46c72c7c-ead0a4e8-85722841-609a0cac': '300',
 '440ad0ec-b8660030-26c4a113-7f3a168d-30bb57a7': '276',
 '900a42fb-36665ab1-4cd371ff-9bf303d4-301ee425': '1078',
 'b0337db1-781931ff-836aaf58-5dd4d131-9bb5f579': '1182',
 '740901ec-b50ce949-ea0c1713-aef69f8c-2069e2f8': '658',
 'eb97f53f-1ed47aff-12a60999-2f7a05b5-2253b113': '694',
 '1ea6e00b-ce50261c-6eee6f16-316afde6-3a8c9aef': '1578',
 '076f6afe-617d6e3e-3d400b70-0a000190-f6e56682': '847',
 '73886d80-588bdfd2-0ee3025c-871c11ae-9fd2d5ec': '989',
 'f4899597-0754a474-8e8785a4-6da852ef-e1b779f0': '1391',
 '6f47dd21-fb381aa5-a6c3de41-ef2d6b13-551c7a1d': '208',
 'fe8d999a-2627d138-daa0885f-c593be05-6ae210f6': '1536',
 'b074b96f-18d5698c-9308ca22-8b7652aa-50445d55': '685',
 '36506dfa-2c580c59-0f13c306-d6127025-e8d593e8': '832',
 'a34e2c18-45871ca9-2b81aa07-8f2c37cf-0318b238': '1244',
 'd7ecc270-1005abdb-e17bc4da-79678d79-992cc8ed': '797',
 '2e712527-347271e9-2139f238-756ab021-96dbd58a': '265',
 '587907fd-ea3401ca-c126576e-1d982fd3-74978dfb': '1156',
 '04df0cf0-8946b0da-fae06114-89d54fa0-46353bbc': '886',
 'b8679479-84a6bc83-6254d9b1-5fb9c697-9e9dbb1d': '625',
 '1e8b16a8-3b6bc5fd-06779f86-6ec866e5-21c8b1f6': '1643',
 '81c451d7-63ad3b15-2730875c-d30ef4c4-7beb1f0b': '1461',
 '09efaaf6-0cd6e473-a1c9c639-93a6c720-00fe0276': '1179',
 '6ef37b47-caf362f6-51af231a-4741641d-520d9c90': '803',
 'ce5f9b19-564d80d6-2b4b41a8-f17d4c2b-48c54b6b': '336',
 '60e88e2c-2052ed7e-73d43ed7-ef7f2499-b7adc027': '346',
 '1df2a972-22b76cbd-7b65aa78-c7c2230d-8ed269f5': '750',
 '88457a10-0c7318bd-0751c33b-c6aa010c-93a9bfad': '1223',
 '3ed43e20-c1f0b29f-ab22c478-43b53e16-e209840a': '1375',
 '40bfefc3-1c52cbc7-dcb01f36-c8bdcbfa-a4850a2b': '1019',
 'd34dfe3f-e181daa6-61f9eb24-ec75f892-490d5bc7': '458',
 'fa33e1c3-6b990d95-aa0413ea-4284bf47-11028411': '370',
 '91899472-090458e7-a8c2a574-d0a011c5-0b571cd7': '273',
 '6ffc5302-7626e3ff-a7f3d90c-9be38251-22dd1917': '996',
 '907a9819-7e39eea1-73822b42-556dc9ad-4f153a01': '1592',
 '1c8ce96c-a7d82764-f54bd4cc-c4a437d4-b15f6056': '1417',
 '9335c736-a4586eec-1abf35fb-9b05dfc0-c6fababe': '588',
 '75b64f36-b123a259-617826ba-b7070175-2fea0131': '1528',
 'a915996b-3f931591-c15a7a8e-ef53db17-89ecae75': '1305',
 '6a119869-ec953f2c-6591ca62-c742c7a4-e7066845': '594',
 '03872a9b-1cc3d7de-da10c68c-b16cf7d7-95fa7fad': '356',
 'd1042924-bd1d4818-0dcd59d9-90cbe6ac-d9110f8d': '1493',
 '62d5f4ac-8ff076c0-72858697-dbfc40b6-770637ce': '1769',
 '596891d5-e7af3f3b-34a7ae69-4de236ee-67d89ff5': '900',
 'd785cc25-8c1f922d-26bffb24-226ad121-0bb54df5': '689',
 '2fa8d544-40e594c0-127bd567-8bba1d6b-8b685b28': '1475',
 '1b43f18f-39c36e5f-e3a8423a-c35e4c7c-fc68fba6': '254',
 '7562bd21-e117f2f5-a9e06568-6b4e3b2f-4629a8ef': '214',
 '4afae95c-5aa88900-9d67df8f-812815ac-6cf50c4d': '491',
 '017d71c4-d5cfb239-2d767a03-d82f6ff4-44052953': '1445',
 '045d44f2-e1f0f7c8-3918f670-7ebc9b05-6e16736c': '894',
 '7ebb17cf-2e6d0a6a-eb27f6ba-0432a940-334a0ff1': '1061',
 '86e09b2a-964f1e72-f5e48129-240d3885-fddaea1d': '222',
 '129a8c02-0128c8ee-4a7935e2-30a02340-a72c4342': '836',
 'ee5fc1d4-c8483db9-42ec0ea5-709755dc-d34f82eb': '1320',
 '4831fea2-301ba608-2e0d01cc-8bdd5726-570d1a26': '1737',
 '453750c2-69dd8f4a-d87be90b-f9ce0b25-6b8f6a6d': '714',
 'd0fcd3bf-a0f2ef64-2f7931ec-28e68412-c0e2a63a': '1224',
 '6fc4aba8-436944ab-548df4ca-3ce62fd2-a5d15e9e': '327',
 '95dc375a-31580286-8f923162-10c3e91d-20c822ec': '1042',
 'ca91a64b-95e14120-f68c63c1-0e310c27-7487fcc0': '817',
 '820ff228-66ef087b-5a3b1fae-a14f18de-32295430': '367',
 '67fb62e0-95fc3700-9dc175d4-d801bd9e-7b1b470b': '1122',
 '71cdbf81-6f74519f-8c8250d5-fc1087e8-d14838d9': '369',
 '84a97c1f-5907dcaf-33e56561-62a56fa7-5676f2f4': '1686',
 'ce6deea8-117af6fa-08ef6551-15ba4f40-4ae119ce': '1433',
 'c19aae90-3931bfc8-9bc8fbfc-3b6bb72c-d78aba7b': '272',
 'be818e1f-3ba69c9c-e51a17b7-6c1c2839-7c3e0294': '1222',
 'eb280dd5-4d51e268-901b868d-657d0d7d-8af8e511': '1237',
 '4faebe8c-8678a47f-a9f54225-cbaf9346-9a2eb5ed': '986',
 'b172e084-61708876-5cb503da-b65f4f85-e1c4e110': '1071',
 'c031cb40-8e35acfd-40f85026-cca26653-84b07124': '1491',
 'b87479c8-641ec909-8b8effc1-9b58a18a-573f8414': '1349',
 '66e2c429-b06ee5eb-cdafa301-4165133d-ffd2d60f': '957',
 'f92bfaf7-ccdb6a73-ff766b2d-b069e9aa-d306e583': '341',
 '53b29019-150a597d-5b513299-f4503515-2e4d5ce2': '1108',
 '47c555b9-f6e07626-191c55a8-19e620bc-1264a40a': '978',
 '529b64f0-ced24e22-c9737bb1-ba33c6de-5f82fd84': '483',

In [111]:
file2id

{'1010': '06dbf910-de873462-8d4f145e-06ed168b-84f1db1b',
 '562': '9bd347a9-7390ce38-7858ffa3-b953e50c-602ca9c0',
 '669': 'e1554ec6-338ebdbb-f55dfa4f-d84b87c9-ed5a22c6',
 '1324': '34df6676-5670b64e-9d17e380-dca30921-e522d0d5',
 '654': '9bd68ca9-a86cecf0-0f4b6910-55e449b4-a5740284',
 '1233': 'd89acb49-fdcbf1f7-9c244597-b0030755-56b15c45',
 '504': '6eed0b1d-6fb9e768-dca6a632-340b8cf3-2cfcbec5',
 '1767': '64122245-5f6ddf0e-e3dc9646-7dde4fd6-0fcda932',
 '923': '4a9d2af0-ccbd9500-2e680ae7-bdcb898e-4b18f321',
 '1290': '33027036-5c1b9e3b-eba9b201-1e94900f-a35bdf50',
 '709': '852f330a-1bc32934-5a7055bc-09d37959-fb9ff5ee',
 '662': '00f0d649-7c3c519a-724d9e2b-f6a90361-7ed8e91f',
 '589': '45eaa40b-6d19c96a-1ff33292-f9651914-386a9104',
 '396': '38b0afbf-b3f9f98e-7d99a144-be80caed-a457f7c3',
 '218': 'e0f89eea-4c053a9d-71c0e76a-e0438014-90dde32c',
 '1616': '9160bb66-bff1151d-dcaf52bf-95fd9015-fc379184',
 '1140': 'e53a9958-547341d7-eec154b3-1191495f-c4e6ff1b',
 '1412': 'bf18ccf8-e703975a-7e41c367-d6579604-6483a1d4',
 '1276': '4b2f339a-85927c6e-441d146b-f9ba37cb-1306af70',
 '911': 'f2251653-53afe4c3-e390d415-4c704ae2-3d0d3cb0',
 '946': 'bccd8be9-dc29cb58-2fe06c1a-a46a85d0-8edc4cb3',
 '1726': '4b2bcc7a-3d1e87d1-fcf7ecf3-699fc4eb-5eba3f1a',
 '1535': '47691f6c-5b59d434-0aad72b4-8b1e5a52-1a31ebbb',
 '1550': '6ff62503-04601df7-1104f334-d26ebc91-a37f2c34',
 '1022': '33b7cbaa-76646fe4-3b1da249-c6b8ac17-c7967cf8',
 '1626': 'e71e9bde-ec3e80e2-df2a795a-688f45a9-c4813443',
 '769': 'bc08a8aa-0a3a0516-70581584-39d0206c-659480ae',
 '1050': 'e8e36663-b29b20eb-36cd48e0-9cc7996e-4883c9ea',
 '1595': '368a5318-1a4e6864-a3cd4e0c-3bf79ae6-aa58b662',
 '1717': '27bfb8ae-0f5bc8a7-86dc760c-fb9f9f04-3e9c0d22',
 '593': '092768a8-29e55f2a-840a0fa4-7d2143a8-589ac90d',
 '644': 'abf8491a-d1c051fa-4a82b92a-454c7898-a8b5f8d1',
 '963': '8dbcc506-88d665aa-758f8bf0-c86ca2be-358eff37',
 '819': 'ab3308a4-8d085219-ad7ea17e-480846b5-bc5f2981',
 '1519': '84626eff-8b540588-5086326d-320d1ad3-91ed3792',
 '192': 'a393e3fa-56095165-eb554350-cf744b58-ca5028e0',
 '1473': 'b5c3083c-492d4520-f926cbe8-6da6f12f-c9413b9a',
 '998': '3f3c0b5a-e6630b26-53079866-423b2546-b61f03e4',
 '191': '267b86fb-64c2754d-00020126-60d16ff0-98efe3ff',
 '777': 'fa23ac67-a5f39449-280e3aac-a77160af-53c1b9f7',
 '825': 'be4c565b-eff4aa0e-aedb1e71-f4ed88ca-96f05b10',
 '513': '8849a85a-68481d1a-846af63f-975aca00-513fdd83',
 '207': 'a6a60ba2-63551bd0-ab1f9bd2-262b6408-4ea8080e',
 '918': 'eb600c81-17c4df39-d7e90a5c-ec587f9a-950d208b',
 '307': '2dd965ed-78a51137-33e1ea33-1016be50-0dbda07f',
 '1482': 'd2995db1-9d6fec74-df2b5f36-758bca99-d55f41bb',
 '1299': 'f7c17fd7-5751471c-0a13c4e1-03af9c4d-fd104ac6',
 '741': 'a0b31432-9cb34f61-fd2ba0c8-189b4d5c-e8b8abc1',
 '801': '9dcb1da5-a5423f01-41cda63a-1dd28e47-ca841f54',
 '656': '7610266b-ca235fd1-d02b147f-e658c7e4-ac52c728',
 '310': 'bbf8c138-051bfe56-fec5f467-ddf026b3-0b0aadad',
 '927': '6c5d9e01-9955ba75-659c0d91-6db3ab63-4d7adc92',
 '372': '587e1d81-962a01be-660656df-73e37c6c-c64ad1b7',
 '949': '6e814edc-f77408ba-e739786a-d66288da-38fc1bc7',
 '1332': '1b7dd223-3cca1e15-48fe53eb-ac68c9c4-4edf7593',
 '350': '4de46e92-62422284-415e9063-c3d408b4-fa2bf1e7',
 '1005': 'da5f4fff-5095f0ae-cea36cfe-02f7a231-6c8a98e0',
 '1533': 'f4d3f4b2-e6f19b7a-bcba548c-a9c9842d-b7ffbd0b',
 '533': 'a1e397e6-76ae7134-a1b087bd-df002cb4-26d01138',
 '880': '66e47a34-038b3685-e0d112f2-860137fc-6421f3e1',
 '538': 'b11afeea-5674a7bb-19710294-f72abee9-779f6b97',
 '1465': '3981105a-cbbb282c-d0baafe8-f21de654-9aa3a9e4',
 '1702': 'f2df5678-09a233da-3c24f8e5-e128dcf9-0823c883',
 '566': '054cb8e0-98ae6171-2a227a59-850dc384-a7b06c85',
 '821': '4c87e3fc-9f8b1cc5-ec2c398f-fe9ab4ed-edcad99a',
 '1063': 'c6232b0a-6ed5e249-6d7ff895-182277ae-d5af0cff',
 '1762': '409fd369-72cad27c-cd7bb5c1-1644baa9-93a3c4b0',
 '1459': 'ae52839f-71db02c9-dcf47606-e9824f11-673f5cd4',
 '329': 'd84c77df-b19570f9-24c0e7d7-6ca3698b-88f1e52c',
 '734': '61fad5c6-668de0b5-0dc0ca38-fb301c1f-f844e42d',
 '1292': 'dd860e6a-2003e499-ab87151e-7e30cfa4-e318f42d',
 '1399': '197f8978-e75ada22-082a0fd1-33b6450f-7b74766b',
 '348': '86217a99-85619185-6a84c88b-be5bba17-2ee4d32d',
 '823': 'b9076c8c-0109ac9e-57274290-45bca4bd-2d59f40e',
 '1230': '96e0f53f-17f98ef2-056176a6-0269d93e-0b4f334e',
 '590': '867aa61f-59e393e4-ea55df7c-4870afe7-ef65d57c',
 '328': '3e933062-0cb72fab-bcea413b-79beaa2d-f216915e',
 '1419': '4e1ae26b-14869d0b-2f6438fa-a294c86f-cceeeaaf',
 '570': 'b67a0174-3a5e2c8a-a7ef9283-5dadf41c-cd41056c',
 '944': '298801b7-ab81f6a0-0703b0a0-0add9ede-bd42f3a0',
 '343': '4553611b-14b3e6a0-45ea463a-5cc4d855-00654b07',
 '1175': '9b5add71-b4c29c77-c8c30a03-2f49771f-a31b45ff',
 '198': '6bff0373-3784fe78-09b9df31-b7652e5f-cd119a62',
 '408': 'ee1769c5-189b12d7-187a454e-f13189f4-19f82052',
 '1435': 'd6bbe37d-0679d1ed-59fa1160-6d6d71d9-cabf73b2',
 '1725': '1eed16d8-e959ea95-474a15c2-77aaa494-303d4d17',
 '1126': '21bee239-226d7b3d-4a4e699f-dc499878-67997d15',
 '166': '44a28d4d-715fb1d1-a27b6b74-8453221e-971636d2',
 '1386': '30014fb7-045e3540-c8cd396c-7f653572-b851b829',
 '1318': 'fccc4b25-6ac728a9-6d0fc4d4-63144f82-d12a6fb4',
 '1007': '9793f12d-80c566d2-b39a1a66-3a354507-fc37ecdc',
 '323': 'f25e8e4d-a80e9f9b-a7d14884-02594a7d-d5496f72',
 '683': 'd774ee4e-cb8ade00-d34d5dc7-29878d4e-eadf38b7',
 '1040': '2e8ef824-29b8fe5d-4a4c8446-065ce060-7d159f5d',
 '739': '015eb5c9-31cf95d7-d19495f0-990442a9-52d4b6b0',
 '433': '96be73d4-3f44b129-bd2270e1-fd971e38-27ee1dfc',
 '337': '8e12c683-e48c0092-779fd1b3-5e7bc494-7e227a95',
 '866': 'cb2881a0-6b7c740f-81d3c742-c9307dfe-89fb6f44',
 '684': 'd997768a-f47363a7-ff81b1db-bb187c51-3145d2b0',
 '885': '02d5ee83-c3b0fb53-368826a5-5f69a6f2-d4d5bdbc',
 '615': 'ff891e58-3a7eec4d-9a3897fe-1de6db9d-5c988f77',
 '480': '22e42fbe-2f5e8375-337266d7-9610b183-a923614e',
 '704': '9a9fdbb3-1346ed62-f6201e73-cab5b89b-728b2400',
 '697': '089d384c-ee81b966-63de481f-b818da02-988568fe',
 '221': '7b2563e2-796b12c0-5ca8a153-17618566-6da77739',
 '1238': '44c7f59a-206ec1b0-dd5f19fa-dc5372c8-18292bac',
 '617': '3666ee86-16e754ac-eab6e6d2-4b0ed1a8-52504d30',
 '1679': '79d4d154-6d2f7c22-1d08f900-61553d08-c7c32819',
 '1082': '17323508-ce40ae57-8c616468-9909663d-eff493d2',
 '1759': '4bb11e84-e7892094-557e839e-77bdd97d-5e1fe4ea',
 '1541': '11b3d5a0-08aadacd-d773d5d7-9f251461-70f6740d',
 '487': '218a0c08-8d9e7d76-283a01e8-5c244cb7-95c3eb6c',
 '1032': '427bf2d0-eed4925a-8a094d07-93f5e700-8da3bc5b',
 '780': '37bd3c0f-c8a1bd1b-294ac32d-5f16b7fd-34faad5d',
 '183': 'ec78872c-5897c5a5-739813bd-218dac09-9ed9a352',
 '1350': '8e67cb50-292f9ea1-9737d5c1-60375ce6-d0301c93',
 '871': '9b54d992-52acb96c-aee40f18-797d7551-ce0eccc3',
 '1761': '996d4331-82f70f4e-f3f6476f-b91d3f13-b9baf9ae',
 '1164': 'edbbfc2c-2a2cbd05-9829252b-a3165a81-9c8e9efe',
 '1466': '339a7cba-3c54e0d7-ef8ff258-441e3d92-a934491c',
 '442': '403afd2f-18290107-33dbfea0-293697df-4b1d33da',
 '725': '2febe34c-406e522d-9d08417c-0c2040c9-ca136b04',
 '1729': 'c58b3098-96692f31-a8cf3957-0c775be3-ced72325',
 '672': '66c6ca15-563339a8-8e16fbc0-636b507d-6a33a7cf',
 '1714': 'e733fe57-343936b1-5f470fb7-725f5e0d-fb2d81bb',
 '718': 'd340fa9b-d4fd2015-f9d93b4e-60926b0c-b5af4795',
 '807': 'c11146df-85fe4ed6-7d99a1da-48ca9e45-fc963cfc',
 '665': '10043fc6-bef278fa-2836658b-170c217f-fb0e78f3',
 '1272': '9af87346-e7f0b72e-33f95c57-6024992b-aea7d0eb',
 '541': '4d05248c-f24aab8e-80fcefa2-6acdeb29-6bd0299c',
 '1153': '9e5870dc-a072db77-8df0fd85-7725fafb-ffb0a340',
 '1527': 'eb06bfba-6aa1d33a-8abcf7af-459a2f4e-6b21cd87',
 '164': '6679c9ac-ff5b3eee-73520f1e-adf11e7d-4d331dfe',
 '379': '00d2050f-75c4d6d7-225be54b-84be5e5e-64411382',
 '1195': '99af4b63-63f42167-8151ee3e-82024743-f5a2d57a',
 '215': 'bb1647b2-6168d5ea-3939f6fa-167b41ea-fa0575d8',
 '1513': '9980cbc2-7db22fd3-756001cd-b8a5b017-9a8c6dc4',
 '737': '28746722-2936ff66-9d412187-a319fe83-7e8159ab',
 '1152': '37b54328-91f5a3cb-d6c22e88-b6ea5e16-c98966e7',
 '755': 'e948df86-6102ed09-c2af4b7a-236ac364-949b9756',
 '1039': '4f9d582a-c992d94b-6418c65a-8866c929-7a52d395',
 '790': '0cfd868a-c1f44af9-e9004851-7c67bd3c-30dd8c43',
 '1407': '6aa29532-3b8308ab-29cb8dcb-b945bbe7-6ac9fb82',
 '693': '620091f4-d7a76ed2-fd23a402-27646f96-83ee8337',
 '520': '43922aed-313be8c4-588e103d-3a0c046b-2ffccf39',
 '1185': '3656419d-1523529f-f080cc08-ac5fbbf1-441422c8',
 '1393': '56a4e21c-5c1417af-6abd963a-0bc99fb7-d809a93e',
 '948': '9b53a850-50a65b98-373f6fe7-5906ed09-a449a43c',
 '435': '2fc787e7-33b59033-aeb7e765-ee7afe60-c4f17aa3',
 '1265': 'df9d4a11-f8ed5e18-ec1e9e2a-43a0e204-937c3327',
 '1117': 'd5385b6a-d3a569c4-263d8648-14a29c41-23d0da4f',
 '1645': '0528ee18-bd9a1b50-c0dec226-384eed35-341a81c1',
 '794': '2f9e57cf-19dd0ee8-c7c2e09a-79271eb5-f64fc781',
 '1452': '6c656abe-12fa280d-5fef7a26-5d4964d9-6bf40ec3',
 '1322': '8e2ac118-83717c3f-07cc8d0e-1a1516f5-9c06ba0a',
 '1649': '5e1396ef-1a3ad447-9d4ce7f5-6e5ee6eb-d9c90343',
 '1560': '213a67df-036236fb-c1837d49-089678a9-0d7cbb1b',
 '822': 'd23f501b-9f497f7e-bf745487-cc353987-33ff7a5c',
 '1062': 'c8e28ce1-b2d94170-8c5d5957-ee8fa58c-f33c6875',
 '1621': '95ceb1b8-5be7722a-2efdde95-f0c0e27e-1ac5b08b',
 '558': '699a54ce-60d2b6d0-a986e38b-af4d2f11-eebbf8ca',
 '786': '52b3eaf8-2ead1702-a717490c-2eb2e329-5de739b4',
 '1334': '6fdfb111-99431e7b-c05f0bda-4d1acb7e-88c8f8f8',
 '1700': '95a6ee94-e07c3d16-5d354c84-cd6ab4a4-d0ee04e3',
 '1319': '83400e5d-6f5ad608-c96e7ed8-b6762a8c-8bee2ae2',
 '724': '37f351a7-db70219d-d966e00c-867d9e4c-bc81a66f',
 '1376': '06509c01-b52e7de6-a0755e96-9b574935-cea8af70',
 '1257': 'd5e797f6-384053b0-deea9356-2125f6f0-44c13808',
 '420': '11032733-26492d86-4fdeecc3-cba8a55e-4cc7687b',
 '406': 'd3ef053b-fc3583c4-ea572369-c703358b-4d714ca4',
 '975': '1ecd8590-a4b58359-30292d24-bc850d05-39d0d4e9',
 '548': 'ec84b311-4f89bd80-bfd691ed-bb1cd2f4-c700b95c',
 '1263': '4316e9f1-a1fca3bc-578a7f99-ecd1d690-2b981969',
 '1377': 'a58842c3-2665d0f8-65c9d0f8-9c6020c7-133daa35',
 '1255': '60fd9e20-0c5de7e5-1a4486e0-9970ec58-d3881e7d',
 '1348': '38bb3ae3-74bc478c-bfabf1d2-09e41e1b-7c75ff40',
 '1149': '951f732e-825f0770-0017eec3-826fbc12-95486a8b',
 '1086': '4e3f4548-c4afb332-f3f8d2ca-5d86602f-89f26f99',
 '429': '0a15351a-1c94e3c3-545b0f91-9afeca42-7d3e1cac',
 '517': '3e2e59d3-a182cdd1-c9e112e2-cb23c4cd-b7ed6cc1',
 '612': '166e491c-cd824e7b-31deb77e-58c41c5c-6ca420db',
 '1252': 'ae9b540d-60191f17-3e3a1f1a-b21bc6ef-d2ceb6ea',
 '248': '164751e1-d6db08f6-8eea8b79-a2ef609c-362a8321',
 '563': 'b44d8b91-7f8d2d29-c04a63a5-e5b8f087-dbcaec1d',
 '1293': '97ed3098-0ffb7f4e-8398f4b0-71ae3079-e5c1d3d9',
 '1657': '51766a8c-931608ef-0863171e-6d9d0cfb-e2f22214',
 '225': 'a2a42680-e0608ab1-2a69fe41-032598e6-1b350022',
 '500': '5a6700b2-974ebbd9-980ef4a6-3bdc7abc-500acf3f',
 '1135': 'd851c679-a021649a-0cd72149-2ed38775-1486eaf0',
 '935': '6357065f-55d036be-03e1d8ba-b0dc8505-c4d562c6',
 '640': '76d7b2a3-99602baa-32b0f82b-22b6cd5f-6f9a6391',
 '529': 'ae4130ac-1c57b6ba-1087205e-75147ea8-2827e002',
 '1489': 'b8886e1f-bddc37c7-4fd67ab6-281cd219-4c8fc2bc',
 '526': '70976df6-8bf40b38-8433bcab-b442dd28-3067e49f',
 '1440': 'fb14ef5d-3a5e0205-e5043d31-c95388d5-d268c744',
 '1748': '40758145-715ae0bf-fbde6208-370e5c69-33166290',
 '1507': '1bde6ab5-7509f442-2ec69d48-d3699783-24d04228',
 '1209': 'bb0cf8af-40de6dcb-41907224-c36645c9-88795f5b',
 '292': '50f2ec2a-85595e1f-0cfacf8d-5bc4fdd7-9b2ff3c9',
 '1744': 'cfdab662-d07df354-7faa8480-5f62d062-e621720c',
 '1053': 'a10539e5-b7980ddd-335d9702-dbbb8585-a323a6a2',
 '1343': 'ef4fe077-de0ddf93-49e581eb-dcf97cc4-3530b6f6',
 '670': 'a2e304d1-2514af76-ecc94dba-b02dc2f0-dab26cfe',
 '839': 'b42c105c-4d79cfe9-48687e06-c7f54db5-322e43c5',
 '470': '1dc4ba46-70c10999-04b3c2df-159bbfbb-78581e9d',
 '1236': '08a041c8-97937962-cd837337-915194de-2867a287',
 '1633': '92dab6c7-d128b001-5b24c76d-0076144e-4cdeadc8',
 '1471': 'eb196f49-e0565d25-87da8a2e-1ec37bc0-611baf58',
 '1172': '8d401a9b-59539a96-42feeeb5-d974a3ec-bae581f2',
 '1722': '016c4716-a6c535d6-35680437-01e476ef-116d732e',
 '1624': 'a174b6e3-732267ea-15cb7b70-06bcedf6-aaff4f51',
 '1701': '1e10f627-7db18f5d-ce6b3364-ef86c8fa-61012f5d',
 '1632': '382afc28-eda672a4-7a4f5c5e-cad16603-5360b95e',
 '197': '4d3647c4-ec43e4da-9ac736e1-93f4e3f4-ad1ff84e',
 '368': '4d520c94-7c68806f-c604a1fc-9678cd29-3216a33a',
 '557': '77ae1182-a7669060-7a7119ac-8aea04f6-d92fef2f',
 '1151': '9f4788af-320c1f28-6a30ca7b-a7bc2318-4341b6e1',
 '243': '23698a3b-71e234ac-db7ced18-262c0eee-bef83ae8',
 '391': '5e28bc57-30e1abd2-a0a7d856-4fc1af1e-5bee10d2',
 '161': 'df197ff2-850f98d6-b2387220-e73af43c-4608190c',
 '1397': 'aaa749a8-1530bfb2-c2b8703d-fe731dd0-d9b7fda9',
 '893': '39083e0f-e59eb98f-a8ff93a9-1ff0d24b-9cba986d',
 '1554': 'aca91b0c-f88649a2-1f20d111-352aac5f-92ba99e0',
 '412': '1541a4b6-f7f308c1-9e017a0a-d247bc16-e3117067',
 '452': 'd418a5d9-d6127db5-65fd4baf-1747ca06-b9d36205',
 '469': '1ac424ef-10a55f7f-7217fad9-76caca35-3f2367ea',
 '1186': 'f2a04bcb-85195f0f-9f0d8090-8ed66f9e-9201f3e8',
 '1206': '7892316c-4de11d73-74c2b0d2-e12848ad-833929c6',
 '1590': 'f9b3c587-eeec9240-8e511516-bd5a2813-d3d9a91a',
 '1356': 'a0466e65-966103ab-41395148-39837993-43240887',
 '345': '77b3f2cd-756cfa0e-38f4c192-640409f5-a43d7a00',
 '1488': '46de32dc-304ace87-3e5d90ec-40c915c5-91080284',
 '1118': '870ce879-8a24a6ed-afb7c8a0-02dd2d45-050d84c1',
 '1439': '3dfac0ba-8df9965d-4e8dd9b0-a488def5-d6fe5585',
 '1037': '2f3b013e-07886489-2c70ff78-76a2e8cd-6920fd8d',
 '1326': '3d8d5cd6-e2d3aa59-944b4be2-267e0366-5dff90d0',
 '648': '83f4bb05-3997aa87-b05aa201-c4dc5c0f-77825f68',
 '1453': '31de2f3e-39f0d82a-6cdd2b60-285f3321-688982de',
 '591': '4f812c6a-11cd7d10-ed0d2d48-02879dec-2f98d5d0',
 '620': '842318b1-6c526f5b-2d39bcea-eac23505-df3ddf37',
 '1017': '5f66b5f6-a5b5e4c5-7e397de4-1da1e37f-6eb45e96',
 '205': 'f5491bc8-aff8bd50-262b248e-fa7a8fbc-21650cf5',
 '580': 'c91297e0-8e2ad563-42ee0d0e-951dad46-45542c17',
 '322': '6f141ea9-abc80bd7-869b724d-c5aebd6e-37d875aa',
 '740': '8efc9cea-d38794e4-5deaf408-4fdd2693-4f4c7dae',
 '1400': 'eefdef6e-ebad18f0-7d4f25d8-ce10dd08-39e00700',
 '1127': '99272cce-314ebb68-7ccda51e-f9e86ce7-f6e592dd',
 '347': '442f77bd-04b8f791-ff1d55f6-b7c40938-f1ff4403',
 '1171': '73401c3f-7d76024c-2b5af59c-dda3c81f-99372ea3',
 '1562': '965b0e30-7c207604-f9bd3831-f51f7c41-bcdd3a49',
 '1563': 'b7a8affd-d43002f9-fda28d6f-75f393d4-ae22e4cb',
 '908': '7d0939f5-bf036d18-c7aa15a2-6baad930-91ab9a3c',
 '876': '0af49fe7-36aea609-c3238542-9305e3b3-5606c349',
 '444': '03a528bc-b97aa2d5-0756cfc0-1dc94a07-094d49a0',
 '522': '06475e5d-0e983e29-638c580e-58ee5a1e-d9250ba5',
 '1361': '4d837680-a00ddaa5-11e47c28-5756fd5a-8eb63ca0',
 '162': '6d955f3c-d72106fa-9acfcafa-9788d41b-95a19124',
 '224': 'f34fd8af-c1044ddc-6d2bd6aa-77732cd4-462e6c8e',
 '405': '7bea5db5-e419ce3d-d25383f3-5c893df7-5acfdc55',
 '1162': 'e785e1ae-4cc6f186-7984308a-d879a1f0-bcd90f94',
 '1092': '84617c12-f019a71d-e60ef99f-40991a4d-eb1ec2a6',
 '305': 'b2f35ad4-4bde53bf-d88b402a-c4c98d1b-60b7154f',
 '1690': '8a2879ba-8f5c49c5-39ae1b13-080d505b-c1ccbb25',
 '951': 'ca38005e-dcc07bad-c1d9b17a-a40ca712-437d0fed',
 '172': '19d44fc4-c57c6fc8-d36493d4-84ffceeb-d6919dde',
 '581': 'bbfad98e-08d00daa-a9f6410a-143e0cf0-a992d206',
 '193': '1daa3b47-4a094f1e-541cffb2-320c4d5a-1f7f9367',
 '505': '2b64ca46-ce632433-25311539-9422211c-35405899',
 '290': '221a1b75-2088d3f7-458d0a6a-7f04e183-b34fd2f4',
 '528': 'a3502cac-e288fded-cb02d222-61b3e3f4-35402df5',
 '535': '4e3cd110-7d87b968-94f0e706-4bb0c0ee-b063ee0f',
 '552': '20c90567-2ce159c5-abc80113-503ecca7-e24c9d6e',
 '203': '3aa18eb0-43ae540c-ca30594d-3b2cc125-5028af82',
 '1567': 'b45e52dd-1d890a59-72c0decc-4cbc0c85-cc8ffc6b',
 '945': 'c734b9ac-2466c26c-5f03c5b7-7f070f49-ef79f88c',
 '450': 'e2940d51-e00b3964-6d225936-895c44ab-bdfd22ab',
 '300': '2c2d93f7-46c72c7c-ead0a4e8-85722841-609a0cac',
 '276': '440ad0ec-b8660030-26c4a113-7f3a168d-30bb57a7',
 '1078': '900a42fb-36665ab1-4cd371ff-9bf303d4-301ee425',
 '1182': 'b0337db1-781931ff-836aaf58-5dd4d131-9bb5f579',
 '658': '740901ec-b50ce949-ea0c1713-aef69f8c-2069e2f8',
 '694': 'eb97f53f-1ed47aff-12a60999-2f7a05b5-2253b113',
 '1578': '1ea6e00b-ce50261c-6eee6f16-316afde6-3a8c9aef',
 '847': '076f6afe-617d6e3e-3d400b70-0a000190-f6e56682',
 '989': '73886d80-588bdfd2-0ee3025c-871c11ae-9fd2d5ec',
 '1391': 'f4899597-0754a474-8e8785a4-6da852ef-e1b779f0',
 '208': '6f47dd21-fb381aa5-a6c3de41-ef2d6b13-551c7a1d',
 '1536': 'fe8d999a-2627d138-daa0885f-c593be05-6ae210f6',
 '685': 'b074b96f-18d5698c-9308ca22-8b7652aa-50445d55',
 '832': '36506dfa-2c580c59-0f13c306-d6127025-e8d593e8',
 '1244': 'a34e2c18-45871ca9-2b81aa07-8f2c37cf-0318b238',
 '797': 'd7ecc270-1005abdb-e17bc4da-79678d79-992cc8ed',
 '265': '2e712527-347271e9-2139f238-756ab021-96dbd58a',
 '1156': '587907fd-ea3401ca-c126576e-1d982fd3-74978dfb',
 '886': '04df0cf0-8946b0da-fae06114-89d54fa0-46353bbc',
 '625': 'b8679479-84a6bc83-6254d9b1-5fb9c697-9e9dbb1d',
 '1643': '1e8b16a8-3b6bc5fd-06779f86-6ec866e5-21c8b1f6',
 '1461': '81c451d7-63ad3b15-2730875c-d30ef4c4-7beb1f0b',
 '1179': '09efaaf6-0cd6e473-a1c9c639-93a6c720-00fe0276',
 '803': '6ef37b47-caf362f6-51af231a-4741641d-520d9c90',
 '336': 'ce5f9b19-564d80d6-2b4b41a8-f17d4c2b-48c54b6b',
 '346': '60e88e2c-2052ed7e-73d43ed7-ef7f2499-b7adc027',
 '750': '1df2a972-22b76cbd-7b65aa78-c7c2230d-8ed269f5',
 '1223': '88457a10-0c7318bd-0751c33b-c6aa010c-93a9bfad',
 '1375': '3ed43e20-c1f0b29f-ab22c478-43b53e16-e209840a',
 '1019': '40bfefc3-1c52cbc7-dcb01f36-c8bdcbfa-a4850a2b',
 '458': 'd34dfe3f-e181daa6-61f9eb24-ec75f892-490d5bc7',
 '370': 'fa33e1c3-6b990d95-aa0413ea-4284bf47-11028411',
 '273': '91899472-090458e7-a8c2a574-d0a011c5-0b571cd7',
 '996': '6ffc5302-7626e3ff-a7f3d90c-9be38251-22dd1917',
 '1592': '907a9819-7e39eea1-73822b42-556dc9ad-4f153a01',
 '1417': '1c8ce96c-a7d82764-f54bd4cc-c4a437d4-b15f6056',
 '588': '9335c736-a4586eec-1abf35fb-9b05dfc0-c6fababe',
 '1528': '75b64f36-b123a259-617826ba-b7070175-2fea0131',
 '1305': 'a915996b-3f931591-c15a7a8e-ef53db17-89ecae75',
 '594': '6a119869-ec953f2c-6591ca62-c742c7a4-e7066845',
 '356': '03872a9b-1cc3d7de-da10c68c-b16cf7d7-95fa7fad',
 '1493': 'd1042924-bd1d4818-0dcd59d9-90cbe6ac-d9110f8d',
 '1769': '62d5f4ac-8ff076c0-72858697-dbfc40b6-770637ce',
 '900': '596891d5-e7af3f3b-34a7ae69-4de236ee-67d89ff5',
 '689': 'd785cc25-8c1f922d-26bffb24-226ad121-0bb54df5',
 '1475': '2fa8d544-40e594c0-127bd567-8bba1d6b-8b685b28',
 '254': '1b43f18f-39c36e5f-e3a8423a-c35e4c7c-fc68fba6',
 '214': '7562bd21-e117f2f5-a9e06568-6b4e3b2f-4629a8ef',
 '491': '4afae95c-5aa88900-9d67df8f-812815ac-6cf50c4d',
 '1445': '017d71c4-d5cfb239-2d767a03-d82f6ff4-44052953',
 '894': '045d44f2-e1f0f7c8-3918f670-7ebc9b05-6e16736c',
 '1061': '7ebb17cf-2e6d0a6a-eb27f6ba-0432a940-334a0ff1',
 '222': '86e09b2a-964f1e72-f5e48129-240d3885-fddaea1d',
 '836': '129a8c02-0128c8ee-4a7935e2-30a02340-a72c4342',
 '1320': 'ee5fc1d4-c8483db9-42ec0ea5-709755dc-d34f82eb',
 '1737': '4831fea2-301ba608-2e0d01cc-8bdd5726-570d1a26',
 '714': '453750c2-69dd8f4a-d87be90b-f9ce0b25-6b8f6a6d',
 '1224': 'd0fcd3bf-a0f2ef64-2f7931ec-28e68412-c0e2a63a',
 '327': '6fc4aba8-436944ab-548df4ca-3ce62fd2-a5d15e9e',
 '1042': '95dc375a-31580286-8f923162-10c3e91d-20c822ec',
 '817': 'ca91a64b-95e14120-f68c63c1-0e310c27-7487fcc0',
 '367': '820ff228-66ef087b-5a3b1fae-a14f18de-32295430',
 '1122': '67fb62e0-95fc3700-9dc175d4-d801bd9e-7b1b470b',
 '369': '71cdbf81-6f74519f-8c8250d5-fc1087e8-d14838d9',
 '1686': '84a97c1f-5907dcaf-33e56561-62a56fa7-5676f2f4',
 '1433': 'ce6deea8-117af6fa-08ef6551-15ba4f40-4ae119ce',
 '272': 'c19aae90-3931bfc8-9bc8fbfc-3b6bb72c-d78aba7b',
 '1222': 'be818e1f-3ba69c9c-e51a17b7-6c1c2839-7c3e0294',
 '1237': 'eb280dd5-4d51e268-901b868d-657d0d7d-8af8e511',
 '986': '4faebe8c-8678a47f-a9f54225-cbaf9346-9a2eb5ed',
 '1071': 'b172e084-61708876-5cb503da-b65f4f85-e1c4e110',
 '1491': 'c031cb40-8e35acfd-40f85026-cca26653-84b07124',
 '1349': 'b87479c8-641ec909-8b8effc1-9b58a18a-573f8414',
 '957': '66e2c429-b06ee5eb-cdafa301-4165133d-ffd2d60f',
 '341': 'f92bfaf7-ccdb6a73-ff766b2d-b069e9aa-d306e583',
 '1108': '53b29019-150a597d-5b513299-f4503515-2e4d5ce2',
 '978': '47c555b9-f6e07626-191c55a8-19e620bc-1264a40a',
 '483': '529b64f0-ced24e22-c9737bb1-ba33c6de-5f82fd84',

In [112]:
len(set(file2id.values()).intersection(fleni600_ids)), len(fleni600_ids), len(set(file2id.values()))

(638, 638, 1615)

In [113]:
fleni600["zip_id"] = fleni600["pet_id"].map(zips_n_contents)
fleni600

,Unnamed: 0,StudyDate,pet_id,PatientID,PatientSex,PatientName,Conclusion,diag,zip_id
0,238,20200825,625ddb3f-6b6adb4a-0653c1b1-1e566cc8-3fe2fab5,702774,M,WANGER^WALTER ROBERTO,-ALa distribución espacial de los hallazgos ...,AD,399
1,234,20201006,c45568f2-c860c13b-ddabe3eb-7bc72f65-dc96ba33,701575,F,RUBIO^MARIA ALEJANDRA,-ALa distribución espacial de los hallazgos ...,AD,395
2,435,20190426,b0e1b100-f29d020b-07fb9c16-bb41abdc-43d7b0e8,597445,F,BRALO^ALICIA ESTER,-ALa distribución espacial de los hallazgos ...,AD,596
3,247,20200804,ee1769c5-189b12d7-187a454e-f13189f4-19f82052,554900,M,LOBOS^ANIBAL PEDRO,Amiloidosis cortical difusa en el presente e...,AD,408
4,387,20190718,ec84b311-4f89bd80-bfd691ed-bb1cd2f4-c700b95c,655037,F,SANCHEZ^MARCELA ADRIANA,Amiloidosis cortical difusa en el presente e...,AD,548
...,...,...,...,...,...,...,...,...,...
633,165,20210923,55e4e05f-63d7f972-8268b162-88e10c2f-b357b9d5,716430,M,ANTOLIN^ELEODORO JORGE,"La ausencia de PIB en corteza cerebral, al mo...",non-AD,326
634,167,20210920,3e933062-0cb72fab-bcea413b-79beaa2d-f216915e,735946,F,LEJTMAN^BERTA LILIANA,"La ausencia de PIB en corteza cerebral, al mo...",non-AD,328
635,205,20210111,e8c79ba5-6d9dbbda-ee35f81a-fb297bc9-bd605906,702579,M,PARDO^SILVERIO,"La ausencia de PIB en corteza cerebral, al mo...",non-AD,366
636,926,20150915,efbf3dab-14c5c80e-55f0f93d-482237a0-9acc8e1f,212192,M,SACK^AUGUSTO,La ausencia de retención de amiloide disminuy...,non-AD,1087
637,951,20150915,7fb34c5b-122c2b29-27c260a3-d6351b3c-ffddfa6c,212192,M,SACK^AUGUSTO,La ausencia de retención de amiloide disminuy...,non-AD,1112

In [114]:
# "subject_1235_pet.nii.gz" example file
# dataset loading os.path.join(self.data_dir, f"{subject_id}.nii.gz"),

fleni600["Subject"] = fleni600["zip_id"].apply(
    lambda x: f"subject_{x}_pet"
)

fleni600

,Unnamed: 0,StudyDate,pet_id,PatientID,PatientSex,PatientName,Conclusion,diag,zip_id,Subject
0,238,20200825,625ddb3f-6b6adb4a-0653c1b1-1e566cc8-3fe2fab5,702774,M,WANGER^WALTER ROBERTO,-ALa distribución espacial de los hallazgos ...,AD,399,subject_399_pet
1,234,20201006,c45568f2-c860c13b-ddabe3eb-7bc72f65-dc96ba33,701575,F,RUBIO^MARIA ALEJANDRA,-ALa distribución espacial de los hallazgos ...,AD,395,subject_395_pet
2,435,20190426,b0e1b100-f29d020b-07fb9c16-bb41abdc-43d7b0e8,597445,F,BRALO^ALICIA ESTER,-ALa distribución espacial de los hallazgos ...,AD,596,subject_596_pet
3,247,20200804,ee1769c5-189b12d7-187a454e-f13189f4-19f82052,554900,M,LOBOS^ANIBAL PEDRO,Amiloidosis cortical difusa en el presente e...,AD,408,subject_408_pet
4,387,20190718,ec84b311-4f89bd80-bfd691ed-bb1cd2f4-c700b95c,655037,F,SANCHEZ^MARCELA ADRIANA,Amiloidosis cortical difusa en el presente e...,AD,548,subject_548_pet
...,...,...,...,...,...,...,...,...,...,...
633,165,20210923,55e4e05f-63d7f972-8268b162-88e10c2f-b357b9d5,716430,M,ANTOLIN^ELEODORO JORGE,"La ausencia de PIB en corteza cerebral, al mo...",non-AD,326,subject_326_pet
634,167,20210920,3e933062-0cb72fab-bcea413b-79beaa2d-f216915e,735946,F,LEJTMAN^BERTA LILIANA,"La ausencia de PIB en corteza cerebral, al mo...",non-AD,328,subject_328_pet
635,205,20210111,e8c79ba5-6d9dbbda-ee35f81a-fb297bc9-bd605906,702579,M,PARDO^SILVERIO,"La ausencia de PIB en corteza cerebral, al mo...",non-AD,366,subject_366_pet
636,926,20150915,efbf3dab-14c5c80e-55f0f93d-482237a0-9acc8e1f,212192,M,SACK^AUGUSTO,La ausencia de retención de amiloide disminuy...,non-AD,1087,subject_1087_pet
637,951,20150915,7fb34c5b-122c2b29-27c260a3-d6351b3c-ffddfa6c,212192,M,SACK^AUGUSTO,La ausencia de retención de amiloide disminuy...,non-AD,1112,subject_1112_pet

In [ ]:
fleni100.rename(
    columns={
        "pet_id": "Subject",
    },
    inplace=True,
)

In [117]:
fleni100["Group"] = fleni100["diag"].apply(lambda x: "AD" if x == 1.0 else "CN")

In [119]:
fleni100["Group"].value_counts()

Group
AD    71
CN    52
Name: count, dtype: int64

In [121]:
fleni100

,Subject,diag,CSF amyloid positivity (yes/no),PET PiB amyloid positivity (yes/no),CSF,PET PiB,Group
0,b87479c8-641ec909-8b8effc1-9b58a18a-573f8414,1.0,Yes,No,True,False,AD
2,e5a4f8b8-f6ad7d45-52b4b6e8-f3ebf6cd-c8e8f25b,1.0,NaN,Yes,False,True,AD
3,c96cbd4d-f9cfda98-8bd71bc1-e26e87e3-e25c6d50,1.0,NaN,Yes,False,True,AD
4,b172e084-61708876-5cb503da-b65f4f85-e1c4e110,1.0,Yes,Yes,True,True,AD
6,ad80ea14-f27dad6f-3e12c1f0-2993bcc3-4cb99a80,0.0,NaN,No,False,False,CN
...,...,...,...,...,...,...,...
225,a4dc5f48-55b6fe7b-95df4cc2-d1a9765f-acf114ce,1.0,NaN,Yes,False,True,AD
226,24fa2c1d-1218de8c-c96d25cb-28e77c7a-89e0c0a4,1.0,NaN,Yes,False,True,AD
231,1541a4b6-f7f308c1-9e017a0a-d247bc16-e3117067,1.0,NaN,Yes,False,True,AD
232,5e28bc57-30e1abd2-a0a7d856-4fc1af1e-5bee10d2,1.0,Yes,No,True,False,AD
233,625ddb3f-6b6adb4a-0653c1b1-1e566cc8-3fe2fab5,1.0,NaN,Yes,False,True,AD

In [ ]:
fleni600["Group"] = fleni600["diag"].apply(
    lambda x: "AD" if x == "AD" else "CN"
)

fleni600["Group"].value_counts()

Group
AD    341
CN    297
Name: count, dtype: int64

In [122]:
# export to csv
fleni100.to_csv("~/Downloads/Fleni/fleni100/fleni100.csv", index=False)
fleni600.to_csv("~/Downloads/Fleni/fleni600/fleni600.csv", index=False)